services:
  asmr-collections:
    image: ghcr.io/kahosan/asmr-collections:latest
    container_name: asmr_collections
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:secret@database:5432/postgres
      # 从 https://jina.ai 获取 API Key
      - JINA_API_KEY=
    volumes:
      - ./data:/app/data # 数据文件夹，包含封面 covers、转码缓存 transcode_cache 和 SQLite 缓存数据库 cache.db，升级时请迁移这些数据
      # - ./VoiceWork:/media # 左边的路径修改为你本地的音频文件夹路径
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped

  database:
    container_name: asmr_postgres
    image: pgvector/pgvector:pg17-bookworm
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret # 请修改为更安全的密码
      POSTGRES_DB: postgres
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
    restart: unless-stopped
