
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SubtitlesData` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/wasm-compiler-edge"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model SubtitlesData
 * 
 */
export type SubtitlesDataModel = runtime.Types.Result.DefaultSelection<Prisma.$SubtitlesDataPayload>

export type AggregateSubtitlesData = {
  _count: SubtitlesDataCountAggregateOutputType | null
  _min: SubtitlesDataMinAggregateOutputType | null
  _max: SubtitlesDataMaxAggregateOutputType | null
}

export type SubtitlesDataMinAggregateOutputType = {
  workId: string | null
  data: runtime.Bytes | null
}

export type SubtitlesDataMaxAggregateOutputType = {
  workId: string | null
  data: runtime.Bytes | null
}

export type SubtitlesDataCountAggregateOutputType = {
  workId: number
  data: number
  _all: number
}


export type SubtitlesDataMinAggregateInputType = {
  workId?: true
  data?: true
}

export type SubtitlesDataMaxAggregateInputType = {
  workId?: true
  data?: true
}

export type SubtitlesDataCountAggregateInputType = {
  workId?: true
  data?: true
  _all?: true
}

export type SubtitlesDataAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SubtitlesData to aggregate.
   */
  where?: Prisma.SubtitlesDataWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SubtitlesData to fetch.
   */
  orderBy?: Prisma.SubtitlesDataOrderByWithRelationInput | Prisma.SubtitlesDataOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SubtitlesDataWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SubtitlesData from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SubtitlesData.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SubtitlesData
  **/
  _count?: true | SubtitlesDataCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SubtitlesDataMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SubtitlesDataMaxAggregateInputType
}

export type GetSubtitlesDataAggregateType<T extends SubtitlesDataAggregateArgs> = {
      [P in keyof T & keyof AggregateSubtitlesData]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSubtitlesData[P]>
    : Prisma.GetScalarType<T[P], AggregateSubtitlesData[P]>
}




export type SubtitlesDataGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SubtitlesDataWhereInput
  orderBy?: Prisma.SubtitlesDataOrderByWithAggregationInput | Prisma.SubtitlesDataOrderByWithAggregationInput[]
  by: Prisma.SubtitlesDataScalarFieldEnum[] | Prisma.SubtitlesDataScalarFieldEnum
  having?: Prisma.SubtitlesDataScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SubtitlesDataCountAggregateInputType | true
  _min?: SubtitlesDataMinAggregateInputType
  _max?: SubtitlesDataMaxAggregateInputType
}

export type SubtitlesDataGroupByOutputType = {
  workId: string
  data: runtime.Bytes
  _count: SubtitlesDataCountAggregateOutputType | null
  _min: SubtitlesDataMinAggregateOutputType | null
  _max: SubtitlesDataMaxAggregateOutputType | null
}

type GetSubtitlesDataGroupByPayload<T extends SubtitlesDataGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SubtitlesDataGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SubtitlesDataGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SubtitlesDataGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SubtitlesDataGroupByOutputType[P]>
      }
    >
  >



export type SubtitlesDataWhereInput = {
  AND?: Prisma.SubtitlesDataWhereInput | Prisma.SubtitlesDataWhereInput[]
  OR?: Prisma.SubtitlesDataWhereInput[]
  NOT?: Prisma.SubtitlesDataWhereInput | Prisma.SubtitlesDataWhereInput[]
  workId?: Prisma.StringFilter<"SubtitlesData"> | string
  data?: Prisma.BytesFilter<"SubtitlesData"> | runtime.Bytes
  work?: Prisma.XOR<Prisma.WorkScalarRelationFilter, Prisma.WorkWhereInput>
}

export type SubtitlesDataOrderByWithRelationInput = {
  workId?: Prisma.SortOrder
  data?: Prisma.SortOrder
  work?: Prisma.WorkOrderByWithRelationInput
}

export type SubtitlesDataWhereUniqueInput = Prisma.AtLeast<{
  workId?: string
  AND?: Prisma.SubtitlesDataWhereInput | Prisma.SubtitlesDataWhereInput[]
  OR?: Prisma.SubtitlesDataWhereInput[]
  NOT?: Prisma.SubtitlesDataWhereInput | Prisma.SubtitlesDataWhereInput[]
  data?: Prisma.BytesFilter<"SubtitlesData"> | runtime.Bytes
  work?: Prisma.XOR<Prisma.WorkScalarRelationFilter, Prisma.WorkWhereInput>
}, "workId">

export type SubtitlesDataOrderByWithAggregationInput = {
  workId?: Prisma.SortOrder
  data?: Prisma.SortOrder
  _count?: Prisma.SubtitlesDataCountOrderByAggregateInput
  _max?: Prisma.SubtitlesDataMaxOrderByAggregateInput
  _min?: Prisma.SubtitlesDataMinOrderByAggregateInput
}

export type SubtitlesDataScalarWhereWithAggregatesInput = {
  AND?: Prisma.SubtitlesDataScalarWhereWithAggregatesInput | Prisma.SubtitlesDataScalarWhereWithAggregatesInput[]
  OR?: Prisma.SubtitlesDataScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SubtitlesDataScalarWhereWithAggregatesInput | Prisma.SubtitlesDataScalarWhereWithAggregatesInput[]
  workId?: Prisma.StringWithAggregatesFilter<"SubtitlesData"> | string
  data?: Prisma.BytesWithAggregatesFilter<"SubtitlesData"> | runtime.Bytes
}

export type SubtitlesDataCreateInput = {
  data: runtime.Bytes
  work: Prisma.WorkCreateNestedOneWithoutSubtitlesDataInput
}

export type SubtitlesDataUncheckedCreateInput = {
  workId: string
  data: runtime.Bytes
}

export type SubtitlesDataUpdateInput = {
  data?: Prisma.BytesFieldUpdateOperationsInput | runtime.Bytes
  work?: Prisma.WorkUpdateOneRequiredWithoutSubtitlesDataNestedInput
}

export type SubtitlesDataUncheckedUpdateInput = {
  workId?: Prisma.StringFieldUpdateOperationsInput | string
  data?: Prisma.BytesFieldUpdateOperationsInput | runtime.Bytes
}

export type SubtitlesDataCreateManyInput = {
  workId: string
  data: runtime.Bytes
}

export type SubtitlesDataUpdateManyMutationInput = {
  data?: Prisma.BytesFieldUpdateOperationsInput | runtime.Bytes
}

export type SubtitlesDataUncheckedUpdateManyInput = {
  workId?: Prisma.StringFieldUpdateOperationsInput | string
  data?: Prisma.BytesFieldUpdateOperationsInput | runtime.Bytes
}

export type SubtitlesDataNullableScalarRelationFilter = {
  is?: Prisma.SubtitlesDataWhereInput | null
  isNot?: Prisma.SubtitlesDataWhereInput | null
}

export type SubtitlesDataCountOrderByAggregateInput = {
  workId?: Prisma.SortOrder
  data?: Prisma.SortOrder
}

export type SubtitlesDataMaxOrderByAggregateInput = {
  workId?: Prisma.SortOrder
  data?: Prisma.SortOrder
}

export type SubtitlesDataMinOrderByAggregateInput = {
  workId?: Prisma.SortOrder
  data?: Prisma.SortOrder
}

export type SubtitlesDataCreateNestedOneWithoutWorkInput = {
  create?: Prisma.XOR<Prisma.SubtitlesDataCreateWithoutWorkInput, Prisma.SubtitlesDataUncheckedCreateWithoutWorkInput>
  connectOrCreate?: Prisma.SubtitlesDataCreateOrConnectWithoutWorkInput
  connect?: Prisma.SubtitlesDataWhereUniqueInput
}

export type SubtitlesDataUncheckedCreateNestedOneWithoutWorkInput = {
  create?: Prisma.XOR<Prisma.SubtitlesDataCreateWithoutWorkInput, Prisma.SubtitlesDataUncheckedCreateWithoutWorkInput>
  connectOrCreate?: Prisma.SubtitlesDataCreateOrConnectWithoutWorkInput
  connect?: Prisma.SubtitlesDataWhereUniqueInput
}

export type SubtitlesDataUpdateOneWithoutWorkNestedInput = {
  create?: Prisma.XOR<Prisma.SubtitlesDataCreateWithoutWorkInput, Prisma.SubtitlesDataUncheckedCreateWithoutWorkInput>
  connectOrCreate?: Prisma.SubtitlesDataCreateOrConnectWithoutWorkInput
  upsert?: Prisma.SubtitlesDataUpsertWithoutWorkInput
  disconnect?: Prisma.SubtitlesDataWhereInput | boolean
  delete?: Prisma.SubtitlesDataWhereInput | boolean
  connect?: Prisma.SubtitlesDataWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SubtitlesDataUpdateToOneWithWhereWithoutWorkInput, Prisma.SubtitlesDataUpdateWithoutWorkInput>, Prisma.SubtitlesDataUncheckedUpdateWithoutWorkInput>
}

export type SubtitlesDataUncheckedUpdateOneWithoutWorkNestedInput = {
  create?: Prisma.XOR<Prisma.SubtitlesDataCreateWithoutWorkInput, Prisma.SubtitlesDataUncheckedCreateWithoutWorkInput>
  connectOrCreate?: Prisma.SubtitlesDataCreateOrConnectWithoutWorkInput
  upsert?: Prisma.SubtitlesDataUpsertWithoutWorkInput
  disconnect?: Prisma.SubtitlesDataWhereInput | boolean
  delete?: Prisma.SubtitlesDataWhereInput | boolean
  connect?: Prisma.SubtitlesDataWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SubtitlesDataUpdateToOneWithWhereWithoutWorkInput, Prisma.SubtitlesDataUpdateWithoutWorkInput>, Prisma.SubtitlesDataUncheckedUpdateWithoutWorkInput>
}

export type BytesFieldUpdateOperationsInput = {
  set?: runtime.Bytes
}

export type SubtitlesDataCreateWithoutWorkInput = {
  data: runtime.Bytes
}

export type SubtitlesDataUncheckedCreateWithoutWorkInput = {
  data: runtime.Bytes
}

export type SubtitlesDataCreateOrConnectWithoutWorkInput = {
  where: Prisma.SubtitlesDataWhereUniqueInput
  create: Prisma.XOR<Prisma.SubtitlesDataCreateWithoutWorkInput, Prisma.SubtitlesDataUncheckedCreateWithoutWorkInput>
}

export type SubtitlesDataUpsertWithoutWorkInput = {
  update: Prisma.XOR<Prisma.SubtitlesDataUpdateWithoutWorkInput, Prisma.SubtitlesDataUncheckedUpdateWithoutWorkInput>
  create: Prisma.XOR<Prisma.SubtitlesDataCreateWithoutWorkInput, Prisma.SubtitlesDataUncheckedCreateWithoutWorkInput>
  where?: Prisma.SubtitlesDataWhereInput
}

export type SubtitlesDataUpdateToOneWithWhereWithoutWorkInput = {
  where?: Prisma.SubtitlesDataWhereInput
  data: Prisma.XOR<Prisma.SubtitlesDataUpdateWithoutWorkInput, Prisma.SubtitlesDataUncheckedUpdateWithoutWorkInput>
}

export type SubtitlesDataUpdateWithoutWorkInput = {
  data?: Prisma.BytesFieldUpdateOperationsInput | runtime.Bytes
}

export type SubtitlesDataUncheckedUpdateWithoutWorkInput = {
  data?: Prisma.BytesFieldUpdateOperationsInput | runtime.Bytes
}



export type SubtitlesDataSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  workId?: boolean
  data?: boolean
  work?: boolean | Prisma.WorkDefaultArgs<ExtArgs>
}, ExtArgs["result"]["subtitlesData"]>

export type SubtitlesDataSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  workId?: boolean
  data?: boolean
  work?: boolean | Prisma.WorkDefaultArgs<ExtArgs>
}, ExtArgs["result"]["subtitlesData"]>

export type SubtitlesDataSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  workId?: boolean
  data?: boolean
  work?: boolean | Prisma.WorkDefaultArgs<ExtArgs>
}, ExtArgs["result"]["subtitlesData"]>

export type SubtitlesDataSelectScalar = {
  workId?: boolean
  data?: boolean
}

export type SubtitlesDataOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"workId" | "data", ExtArgs["result"]["subtitlesData"]>
export type SubtitlesDataInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  work?: boolean | Prisma.WorkDefaultArgs<ExtArgs>
}
export type SubtitlesDataIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  work?: boolean | Prisma.WorkDefaultArgs<ExtArgs>
}
export type SubtitlesDataIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  work?: boolean | Prisma.WorkDefaultArgs<ExtArgs>
}

export type $SubtitlesDataPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SubtitlesData"
  objects: {
    work: Prisma.$WorkPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    workId: string
    data: runtime.Bytes
  }, ExtArgs["result"]["subtitlesData"]>
  composites: {}
}

export type SubtitlesDataGetPayload<S extends boolean | null | undefined | SubtitlesDataDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SubtitlesDataPayload, S>

export type SubtitlesDataCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SubtitlesDataFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SubtitlesDataCountAggregateInputType | true
  }

export interface SubtitlesDataDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SubtitlesData'], meta: { name: 'SubtitlesData' } }
  /**
   * Find zero or one SubtitlesData that matches the filter.
   * @param {SubtitlesDataFindUniqueArgs} args - Arguments to find a SubtitlesData
   * @example
   * // Get one SubtitlesData
   * const subtitlesData = await prisma.subtitlesData.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SubtitlesDataFindUniqueArgs>(args: Prisma.SelectSubset<T, SubtitlesDataFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SubtitlesDataClient<runtime.Types.Result.GetResult<Prisma.$SubtitlesDataPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SubtitlesData that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SubtitlesDataFindUniqueOrThrowArgs} args - Arguments to find a SubtitlesData
   * @example
   * // Get one SubtitlesData
   * const subtitlesData = await prisma.subtitlesData.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SubtitlesDataFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SubtitlesDataFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SubtitlesDataClient<runtime.Types.Result.GetResult<Prisma.$SubtitlesDataPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SubtitlesData that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubtitlesDataFindFirstArgs} args - Arguments to find a SubtitlesData
   * @example
   * // Get one SubtitlesData
   * const subtitlesData = await prisma.subtitlesData.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SubtitlesDataFindFirstArgs>(args?: Prisma.SelectSubset<T, SubtitlesDataFindFirstArgs<ExtArgs>>): Prisma.Prisma__SubtitlesDataClient<runtime.Types.Result.GetResult<Prisma.$SubtitlesDataPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SubtitlesData that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubtitlesDataFindFirstOrThrowArgs} args - Arguments to find a SubtitlesData
   * @example
   * // Get one SubtitlesData
   * const subtitlesData = await prisma.subtitlesData.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SubtitlesDataFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SubtitlesDataFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SubtitlesDataClient<runtime.Types.Result.GetResult<Prisma.$SubtitlesDataPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SubtitlesData that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubtitlesDataFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SubtitlesData
   * const subtitlesData = await prisma.subtitlesData.findMany()
   * 
   * // Get first 10 SubtitlesData
   * const subtitlesData = await prisma.subtitlesData.findMany({ take: 10 })
   * 
   * // Only select the `workId`
   * const subtitlesDataWithWorkIdOnly = await prisma.subtitlesData.findMany({ select: { workId: true } })
   * 
   */
  findMany<T extends SubtitlesDataFindManyArgs>(args?: Prisma.SelectSubset<T, SubtitlesDataFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SubtitlesDataPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SubtitlesData.
   * @param {SubtitlesDataCreateArgs} args - Arguments to create a SubtitlesData.
   * @example
   * // Create one SubtitlesData
   * const SubtitlesData = await prisma.subtitlesData.create({
   *   data: {
   *     // ... data to create a SubtitlesData
   *   }
   * })
   * 
   */
  create<T extends SubtitlesDataCreateArgs>(args: Prisma.SelectSubset<T, SubtitlesDataCreateArgs<ExtArgs>>): Prisma.Prisma__SubtitlesDataClient<runtime.Types.Result.GetResult<Prisma.$SubtitlesDataPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SubtitlesData.
   * @param {SubtitlesDataCreateManyArgs} args - Arguments to create many SubtitlesData.
   * @example
   * // Create many SubtitlesData
   * const subtitlesData = await prisma.subtitlesData.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SubtitlesDataCreateManyArgs>(args?: Prisma.SelectSubset<T, SubtitlesDataCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SubtitlesData and returns the data saved in the database.
   * @param {SubtitlesDataCreateManyAndReturnArgs} args - Arguments to create many SubtitlesData.
   * @example
   * // Create many SubtitlesData
   * const subtitlesData = await prisma.subtitlesData.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SubtitlesData and only return the `workId`
   * const subtitlesDataWithWorkIdOnly = await prisma.subtitlesData.createManyAndReturn({
   *   select: { workId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SubtitlesDataCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SubtitlesDataCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SubtitlesDataPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SubtitlesData.
   * @param {SubtitlesDataDeleteArgs} args - Arguments to delete one SubtitlesData.
   * @example
   * // Delete one SubtitlesData
   * const SubtitlesData = await prisma.subtitlesData.delete({
   *   where: {
   *     // ... filter to delete one SubtitlesData
   *   }
   * })
   * 
   */
  delete<T extends SubtitlesDataDeleteArgs>(args: Prisma.SelectSubset<T, SubtitlesDataDeleteArgs<ExtArgs>>): Prisma.Prisma__SubtitlesDataClient<runtime.Types.Result.GetResult<Prisma.$SubtitlesDataPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SubtitlesData.
   * @param {SubtitlesDataUpdateArgs} args - Arguments to update one SubtitlesData.
   * @example
   * // Update one SubtitlesData
   * const subtitlesData = await prisma.subtitlesData.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SubtitlesDataUpdateArgs>(args: Prisma.SelectSubset<T, SubtitlesDataUpdateArgs<ExtArgs>>): Prisma.Prisma__SubtitlesDataClient<runtime.Types.Result.GetResult<Prisma.$SubtitlesDataPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SubtitlesData.
   * @param {SubtitlesDataDeleteManyArgs} args - Arguments to filter SubtitlesData to delete.
   * @example
   * // Delete a few SubtitlesData
   * const { count } = await prisma.subtitlesData.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SubtitlesDataDeleteManyArgs>(args?: Prisma.SelectSubset<T, SubtitlesDataDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SubtitlesData.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubtitlesDataUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SubtitlesData
   * const subtitlesData = await prisma.subtitlesData.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SubtitlesDataUpdateManyArgs>(args: Prisma.SelectSubset<T, SubtitlesDataUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SubtitlesData and returns the data updated in the database.
   * @param {SubtitlesDataUpdateManyAndReturnArgs} args - Arguments to update many SubtitlesData.
   * @example
   * // Update many SubtitlesData
   * const subtitlesData = await prisma.subtitlesData.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SubtitlesData and only return the `workId`
   * const subtitlesDataWithWorkIdOnly = await prisma.subtitlesData.updateManyAndReturn({
   *   select: { workId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SubtitlesDataUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SubtitlesDataUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SubtitlesDataPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SubtitlesData.
   * @param {SubtitlesDataUpsertArgs} args - Arguments to update or create a SubtitlesData.
   * @example
   * // Update or create a SubtitlesData
   * const subtitlesData = await prisma.subtitlesData.upsert({
   *   create: {
   *     // ... data to create a SubtitlesData
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SubtitlesData we want to update
   *   }
   * })
   */
  upsert<T extends SubtitlesDataUpsertArgs>(args: Prisma.SelectSubset<T, SubtitlesDataUpsertArgs<ExtArgs>>): Prisma.Prisma__SubtitlesDataClient<runtime.Types.Result.GetResult<Prisma.$SubtitlesDataPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SubtitlesData.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubtitlesDataCountArgs} args - Arguments to filter SubtitlesData to count.
   * @example
   * // Count the number of SubtitlesData
   * const count = await prisma.subtitlesData.count({
   *   where: {
   *     // ... the filter for the SubtitlesData we want to count
   *   }
   * })
  **/
  count<T extends SubtitlesDataCountArgs>(
    args?: Prisma.Subset<T, SubtitlesDataCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SubtitlesDataCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SubtitlesData.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubtitlesDataAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SubtitlesDataAggregateArgs>(args: Prisma.Subset<T, SubtitlesDataAggregateArgs>): Prisma.PrismaPromise<GetSubtitlesDataAggregateType<T>>

  /**
   * Group by SubtitlesData.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubtitlesDataGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SubtitlesDataGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SubtitlesDataGroupByArgs['orderBy'] }
      : { orderBy?: SubtitlesDataGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SubtitlesDataGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSubtitlesDataGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SubtitlesData model
 */
readonly fields: SubtitlesDataFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SubtitlesData.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SubtitlesDataClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  work<T extends Prisma.WorkDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.WorkDefaultArgs<ExtArgs>>): Prisma.Prisma__WorkClient<runtime.Types.Result.GetResult<Prisma.$WorkPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SubtitlesData model
 */
export interface SubtitlesDataFieldRefs {
  readonly workId: Prisma.FieldRef<"SubtitlesData", 'String'>
  readonly data: Prisma.FieldRef<"SubtitlesData", 'Bytes'>
}
    

// Custom InputTypes
/**
 * SubtitlesData findUnique
 */
export type SubtitlesDataFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubtitlesData
   */
  select?: Prisma.SubtitlesDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubtitlesData
   */
  omit?: Prisma.SubtitlesDataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubtitlesDataInclude<ExtArgs> | null
  /**
   * Filter, which SubtitlesData to fetch.
   */
  where: Prisma.SubtitlesDataWhereUniqueInput
}

/**
 * SubtitlesData findUniqueOrThrow
 */
export type SubtitlesDataFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubtitlesData
   */
  select?: Prisma.SubtitlesDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubtitlesData
   */
  omit?: Prisma.SubtitlesDataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubtitlesDataInclude<ExtArgs> | null
  /**
   * Filter, which SubtitlesData to fetch.
   */
  where: Prisma.SubtitlesDataWhereUniqueInput
}

/**
 * SubtitlesData findFirst
 */
export type SubtitlesDataFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubtitlesData
   */
  select?: Prisma.SubtitlesDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubtitlesData
   */
  omit?: Prisma.SubtitlesDataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubtitlesDataInclude<ExtArgs> | null
  /**
   * Filter, which SubtitlesData to fetch.
   */
  where?: Prisma.SubtitlesDataWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SubtitlesData to fetch.
   */
  orderBy?: Prisma.SubtitlesDataOrderByWithRelationInput | Prisma.SubtitlesDataOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SubtitlesData.
   */
  cursor?: Prisma.SubtitlesDataWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SubtitlesData from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SubtitlesData.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SubtitlesData.
   */
  distinct?: Prisma.SubtitlesDataScalarFieldEnum | Prisma.SubtitlesDataScalarFieldEnum[]
}

/**
 * SubtitlesData findFirstOrThrow
 */
export type SubtitlesDataFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubtitlesData
   */
  select?: Prisma.SubtitlesDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubtitlesData
   */
  omit?: Prisma.SubtitlesDataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubtitlesDataInclude<ExtArgs> | null
  /**
   * Filter, which SubtitlesData to fetch.
   */
  where?: Prisma.SubtitlesDataWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SubtitlesData to fetch.
   */
  orderBy?: Prisma.SubtitlesDataOrderByWithRelationInput | Prisma.SubtitlesDataOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SubtitlesData.
   */
  cursor?: Prisma.SubtitlesDataWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SubtitlesData from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SubtitlesData.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SubtitlesData.
   */
  distinct?: Prisma.SubtitlesDataScalarFieldEnum | Prisma.SubtitlesDataScalarFieldEnum[]
}

/**
 * SubtitlesData findMany
 */
export type SubtitlesDataFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubtitlesData
   */
  select?: Prisma.SubtitlesDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubtitlesData
   */
  omit?: Prisma.SubtitlesDataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubtitlesDataInclude<ExtArgs> | null
  /**
   * Filter, which SubtitlesData to fetch.
   */
  where?: Prisma.SubtitlesDataWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SubtitlesData to fetch.
   */
  orderBy?: Prisma.SubtitlesDataOrderByWithRelationInput | Prisma.SubtitlesDataOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SubtitlesData.
   */
  cursor?: Prisma.SubtitlesDataWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SubtitlesData from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SubtitlesData.
   */
  skip?: number
  distinct?: Prisma.SubtitlesDataScalarFieldEnum | Prisma.SubtitlesDataScalarFieldEnum[]
}

/**
 * SubtitlesData create
 */
export type SubtitlesDataCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubtitlesData
   */
  select?: Prisma.SubtitlesDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubtitlesData
   */
  omit?: Prisma.SubtitlesDataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubtitlesDataInclude<ExtArgs> | null
  /**
   * The data needed to create a SubtitlesData.
   */
  data: Prisma.XOR<Prisma.SubtitlesDataCreateInput, Prisma.SubtitlesDataUncheckedCreateInput>
}

/**
 * SubtitlesData createMany
 */
export type SubtitlesDataCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SubtitlesData.
   */
  data: Prisma.SubtitlesDataCreateManyInput | Prisma.SubtitlesDataCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SubtitlesData createManyAndReturn
 */
export type SubtitlesDataCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubtitlesData
   */
  select?: Prisma.SubtitlesDataSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SubtitlesData
   */
  omit?: Prisma.SubtitlesDataOmit<ExtArgs> | null
  /**
   * The data used to create many SubtitlesData.
   */
  data: Prisma.SubtitlesDataCreateManyInput | Prisma.SubtitlesDataCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubtitlesDataIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * SubtitlesData update
 */
export type SubtitlesDataUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubtitlesData
   */
  select?: Prisma.SubtitlesDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubtitlesData
   */
  omit?: Prisma.SubtitlesDataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubtitlesDataInclude<ExtArgs> | null
  /**
   * The data needed to update a SubtitlesData.
   */
  data: Prisma.XOR<Prisma.SubtitlesDataUpdateInput, Prisma.SubtitlesDataUncheckedUpdateInput>
  /**
   * Choose, which SubtitlesData to update.
   */
  where: Prisma.SubtitlesDataWhereUniqueInput
}

/**
 * SubtitlesData updateMany
 */
export type SubtitlesDataUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SubtitlesData.
   */
  data: Prisma.XOR<Prisma.SubtitlesDataUpdateManyMutationInput, Prisma.SubtitlesDataUncheckedUpdateManyInput>
  /**
   * Filter which SubtitlesData to update
   */
  where?: Prisma.SubtitlesDataWhereInput
  /**
   * Limit how many SubtitlesData to update.
   */
  limit?: number
}

/**
 * SubtitlesData updateManyAndReturn
 */
export type SubtitlesDataUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubtitlesData
   */
  select?: Prisma.SubtitlesDataSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SubtitlesData
   */
  omit?: Prisma.SubtitlesDataOmit<ExtArgs> | null
  /**
   * The data used to update SubtitlesData.
   */
  data: Prisma.XOR<Prisma.SubtitlesDataUpdateManyMutationInput, Prisma.SubtitlesDataUncheckedUpdateManyInput>
  /**
   * Filter which SubtitlesData to update
   */
  where?: Prisma.SubtitlesDataWhereInput
  /**
   * Limit how many SubtitlesData to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubtitlesDataIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * SubtitlesData upsert
 */
export type SubtitlesDataUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubtitlesData
   */
  select?: Prisma.SubtitlesDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubtitlesData
   */
  omit?: Prisma.SubtitlesDataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubtitlesDataInclude<ExtArgs> | null
  /**
   * The filter to search for the SubtitlesData to update in case it exists.
   */
  where: Prisma.SubtitlesDataWhereUniqueInput
  /**
   * In case the SubtitlesData found by the `where` argument doesn't exist, create a new SubtitlesData with this data.
   */
  create: Prisma.XOR<Prisma.SubtitlesDataCreateInput, Prisma.SubtitlesDataUncheckedCreateInput>
  /**
   * In case the SubtitlesData was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SubtitlesDataUpdateInput, Prisma.SubtitlesDataUncheckedUpdateInput>
}

/**
 * SubtitlesData delete
 */
export type SubtitlesDataDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubtitlesData
   */
  select?: Prisma.SubtitlesDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubtitlesData
   */
  omit?: Prisma.SubtitlesDataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubtitlesDataInclude<ExtArgs> | null
  /**
   * Filter which SubtitlesData to delete.
   */
  where: Prisma.SubtitlesDataWhereUniqueInput
}

/**
 * SubtitlesData deleteMany
 */
export type SubtitlesDataDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SubtitlesData to delete
   */
  where?: Prisma.SubtitlesDataWhereInput
  /**
   * Limit how many SubtitlesData to delete.
   */
  limit?: number
}

/**
 * SubtitlesData without action
 */
export type SubtitlesDataDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubtitlesData
   */
  select?: Prisma.SubtitlesDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubtitlesData
   */
  omit?: Prisma.SubtitlesDataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubtitlesDataInclude<ExtArgs> | null
}
