
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Circle` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Circle
 * 
 */
export type CircleModel = runtime.Types.Result.DefaultSelection<Prisma.$CirclePayload>

export type AggregateCircle = {
  _count: CircleCountAggregateOutputType | null
  _min: CircleMinAggregateOutputType | null
  _max: CircleMaxAggregateOutputType | null
}

export type CircleMinAggregateOutputType = {
  id: string | null
  name: string | null
}

export type CircleMaxAggregateOutputType = {
  id: string | null
  name: string | null
}

export type CircleCountAggregateOutputType = {
  id: number
  name: number
  _all: number
}


export type CircleMinAggregateInputType = {
  id?: true
  name?: true
}

export type CircleMaxAggregateInputType = {
  id?: true
  name?: true
}

export type CircleCountAggregateInputType = {
  id?: true
  name?: true
  _all?: true
}

export type CircleAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Circle to aggregate.
   */
  where?: Prisma.CircleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Circles to fetch.
   */
  orderBy?: Prisma.CircleOrderByWithRelationInput | Prisma.CircleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CircleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Circles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Circles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Circles
  **/
  _count?: true | CircleCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CircleMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CircleMaxAggregateInputType
}

export type GetCircleAggregateType<T extends CircleAggregateArgs> = {
      [P in keyof T & keyof AggregateCircle]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCircle[P]>
    : Prisma.GetScalarType<T[P], AggregateCircle[P]>
}




export type CircleGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CircleWhereInput
  orderBy?: Prisma.CircleOrderByWithAggregationInput | Prisma.CircleOrderByWithAggregationInput[]
  by: Prisma.CircleScalarFieldEnum[] | Prisma.CircleScalarFieldEnum
  having?: Prisma.CircleScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CircleCountAggregateInputType | true
  _min?: CircleMinAggregateInputType
  _max?: CircleMaxAggregateInputType
}

export type CircleGroupByOutputType = {
  id: string
  name: string
  _count: CircleCountAggregateOutputType | null
  _min: CircleMinAggregateOutputType | null
  _max: CircleMaxAggregateOutputType | null
}

type GetCircleGroupByPayload<T extends CircleGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CircleGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CircleGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CircleGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CircleGroupByOutputType[P]>
      }
    >
  >



export type CircleWhereInput = {
  AND?: Prisma.CircleWhereInput | Prisma.CircleWhereInput[]
  OR?: Prisma.CircleWhereInput[]
  NOT?: Prisma.CircleWhereInput | Prisma.CircleWhereInput[]
  id?: Prisma.StringFilter<"Circle"> | string
  name?: Prisma.StringFilter<"Circle"> | string
  works?: Prisma.WorkListRelationFilter
}

export type CircleOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  works?: Prisma.WorkOrderByRelationAggregateInput
}

export type CircleWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.CircleWhereInput | Prisma.CircleWhereInput[]
  OR?: Prisma.CircleWhereInput[]
  NOT?: Prisma.CircleWhereInput | Prisma.CircleWhereInput[]
  name?: Prisma.StringFilter<"Circle"> | string
  works?: Prisma.WorkListRelationFilter
}, "id">

export type CircleOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  _count?: Prisma.CircleCountOrderByAggregateInput
  _max?: Prisma.CircleMaxOrderByAggregateInput
  _min?: Prisma.CircleMinOrderByAggregateInput
}

export type CircleScalarWhereWithAggregatesInput = {
  AND?: Prisma.CircleScalarWhereWithAggregatesInput | Prisma.CircleScalarWhereWithAggregatesInput[]
  OR?: Prisma.CircleScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CircleScalarWhereWithAggregatesInput | Prisma.CircleScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Circle"> | string
  name?: Prisma.StringWithAggregatesFilter<"Circle"> | string
}

export type CircleCreateInput = {
  id: string
  name: string
  works?: Prisma.WorkCreateNestedManyWithoutCircleInput
}

export type CircleUncheckedCreateInput = {
  id: string
  name: string
  works?: Prisma.WorkUncheckedCreateNestedManyWithoutCircleInput
}

export type CircleUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  works?: Prisma.WorkUpdateManyWithoutCircleNestedInput
}

export type CircleUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  works?: Prisma.WorkUncheckedUpdateManyWithoutCircleNestedInput
}

export type CircleCreateManyInput = {
  id: string
  name: string
}

export type CircleUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CircleUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CircleScalarRelationFilter = {
  is?: Prisma.CircleWhereInput
  isNot?: Prisma.CircleWhereInput
}

export type CircleCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
}

export type CircleMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
}

export type CircleMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
}

export type CircleCreateNestedOneWithoutWorksInput = {
  create?: Prisma.XOR<Prisma.CircleCreateWithoutWorksInput, Prisma.CircleUncheckedCreateWithoutWorksInput>
  connectOrCreate?: Prisma.CircleCreateOrConnectWithoutWorksInput
  connect?: Prisma.CircleWhereUniqueInput
}

export type CircleUpdateOneRequiredWithoutWorksNestedInput = {
  create?: Prisma.XOR<Prisma.CircleCreateWithoutWorksInput, Prisma.CircleUncheckedCreateWithoutWorksInput>
  connectOrCreate?: Prisma.CircleCreateOrConnectWithoutWorksInput
  upsert?: Prisma.CircleUpsertWithoutWorksInput
  connect?: Prisma.CircleWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CircleUpdateToOneWithWhereWithoutWorksInput, Prisma.CircleUpdateWithoutWorksInput>, Prisma.CircleUncheckedUpdateWithoutWorksInput>
}

export type CircleCreateWithoutWorksInput = {
  id: string
  name: string
}

export type CircleUncheckedCreateWithoutWorksInput = {
  id: string
  name: string
}

export type CircleCreateOrConnectWithoutWorksInput = {
  where: Prisma.CircleWhereUniqueInput
  create: Prisma.XOR<Prisma.CircleCreateWithoutWorksInput, Prisma.CircleUncheckedCreateWithoutWorksInput>
}

export type CircleUpsertWithoutWorksInput = {
  update: Prisma.XOR<Prisma.CircleUpdateWithoutWorksInput, Prisma.CircleUncheckedUpdateWithoutWorksInput>
  create: Prisma.XOR<Prisma.CircleCreateWithoutWorksInput, Prisma.CircleUncheckedCreateWithoutWorksInput>
  where?: Prisma.CircleWhereInput
}

export type CircleUpdateToOneWithWhereWithoutWorksInput = {
  where?: Prisma.CircleWhereInput
  data: Prisma.XOR<Prisma.CircleUpdateWithoutWorksInput, Prisma.CircleUncheckedUpdateWithoutWorksInput>
}

export type CircleUpdateWithoutWorksInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CircleUncheckedUpdateWithoutWorksInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type CircleCountOutputType
 */

export type CircleCountOutputType = {
  works: number
}

export type CircleCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  works?: boolean | CircleCountOutputTypeCountWorksArgs
}

/**
 * CircleCountOutputType without action
 */
export type CircleCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CircleCountOutputType
   */
  select?: Prisma.CircleCountOutputTypeSelect<ExtArgs> | null
}

/**
 * CircleCountOutputType without action
 */
export type CircleCountOutputTypeCountWorksArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.WorkWhereInput
}


export type CircleSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  works?: boolean | Prisma.Circle$worksArgs<ExtArgs>
  _count?: boolean | Prisma.CircleCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["circle"]>

export type CircleSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
}, ExtArgs["result"]["circle"]>

export type CircleSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
}, ExtArgs["result"]["circle"]>

export type CircleSelectScalar = {
  id?: boolean
  name?: boolean
}

export type CircleOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name", ExtArgs["result"]["circle"]>
export type CircleInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  works?: boolean | Prisma.Circle$worksArgs<ExtArgs>
  _count?: boolean | Prisma.CircleCountOutputTypeDefaultArgs<ExtArgs>
}
export type CircleIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type CircleIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $CirclePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Circle"
  objects: {
    works: Prisma.$WorkPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
  }, ExtArgs["result"]["circle"]>
  composites: {}
}

export type CircleGetPayload<S extends boolean | null | undefined | CircleDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CirclePayload, S>

export type CircleCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CircleFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CircleCountAggregateInputType | true
  }

export interface CircleDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Circle'], meta: { name: 'Circle' } }
  /**
   * Find zero or one Circle that matches the filter.
   * @param {CircleFindUniqueArgs} args - Arguments to find a Circle
   * @example
   * // Get one Circle
   * const circle = await prisma.circle.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CircleFindUniqueArgs>(args: Prisma.SelectSubset<T, CircleFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CircleClient<runtime.Types.Result.GetResult<Prisma.$CirclePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Circle that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CircleFindUniqueOrThrowArgs} args - Arguments to find a Circle
   * @example
   * // Get one Circle
   * const circle = await prisma.circle.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CircleFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CircleFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CircleClient<runtime.Types.Result.GetResult<Prisma.$CirclePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Circle that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CircleFindFirstArgs} args - Arguments to find a Circle
   * @example
   * // Get one Circle
   * const circle = await prisma.circle.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CircleFindFirstArgs>(args?: Prisma.SelectSubset<T, CircleFindFirstArgs<ExtArgs>>): Prisma.Prisma__CircleClient<runtime.Types.Result.GetResult<Prisma.$CirclePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Circle that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CircleFindFirstOrThrowArgs} args - Arguments to find a Circle
   * @example
   * // Get one Circle
   * const circle = await prisma.circle.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CircleFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CircleFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CircleClient<runtime.Types.Result.GetResult<Prisma.$CirclePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Circles that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CircleFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Circles
   * const circles = await prisma.circle.findMany()
   * 
   * // Get first 10 Circles
   * const circles = await prisma.circle.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const circleWithIdOnly = await prisma.circle.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CircleFindManyArgs>(args?: Prisma.SelectSubset<T, CircleFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CirclePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Circle.
   * @param {CircleCreateArgs} args - Arguments to create a Circle.
   * @example
   * // Create one Circle
   * const Circle = await prisma.circle.create({
   *   data: {
   *     // ... data to create a Circle
   *   }
   * })
   * 
   */
  create<T extends CircleCreateArgs>(args: Prisma.SelectSubset<T, CircleCreateArgs<ExtArgs>>): Prisma.Prisma__CircleClient<runtime.Types.Result.GetResult<Prisma.$CirclePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Circles.
   * @param {CircleCreateManyArgs} args - Arguments to create many Circles.
   * @example
   * // Create many Circles
   * const circle = await prisma.circle.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CircleCreateManyArgs>(args?: Prisma.SelectSubset<T, CircleCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Circles and returns the data saved in the database.
   * @param {CircleCreateManyAndReturnArgs} args - Arguments to create many Circles.
   * @example
   * // Create many Circles
   * const circle = await prisma.circle.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Circles and only return the `id`
   * const circleWithIdOnly = await prisma.circle.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CircleCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CircleCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CirclePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Circle.
   * @param {CircleDeleteArgs} args - Arguments to delete one Circle.
   * @example
   * // Delete one Circle
   * const Circle = await prisma.circle.delete({
   *   where: {
   *     // ... filter to delete one Circle
   *   }
   * })
   * 
   */
  delete<T extends CircleDeleteArgs>(args: Prisma.SelectSubset<T, CircleDeleteArgs<ExtArgs>>): Prisma.Prisma__CircleClient<runtime.Types.Result.GetResult<Prisma.$CirclePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Circle.
   * @param {CircleUpdateArgs} args - Arguments to update one Circle.
   * @example
   * // Update one Circle
   * const circle = await prisma.circle.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CircleUpdateArgs>(args: Prisma.SelectSubset<T, CircleUpdateArgs<ExtArgs>>): Prisma.Prisma__CircleClient<runtime.Types.Result.GetResult<Prisma.$CirclePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Circles.
   * @param {CircleDeleteManyArgs} args - Arguments to filter Circles to delete.
   * @example
   * // Delete a few Circles
   * const { count } = await prisma.circle.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CircleDeleteManyArgs>(args?: Prisma.SelectSubset<T, CircleDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Circles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CircleUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Circles
   * const circle = await prisma.circle.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CircleUpdateManyArgs>(args: Prisma.SelectSubset<T, CircleUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Circles and returns the data updated in the database.
   * @param {CircleUpdateManyAndReturnArgs} args - Arguments to update many Circles.
   * @example
   * // Update many Circles
   * const circle = await prisma.circle.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Circles and only return the `id`
   * const circleWithIdOnly = await prisma.circle.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CircleUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CircleUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CirclePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Circle.
   * @param {CircleUpsertArgs} args - Arguments to update or create a Circle.
   * @example
   * // Update or create a Circle
   * const circle = await prisma.circle.upsert({
   *   create: {
   *     // ... data to create a Circle
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Circle we want to update
   *   }
   * })
   */
  upsert<T extends CircleUpsertArgs>(args: Prisma.SelectSubset<T, CircleUpsertArgs<ExtArgs>>): Prisma.Prisma__CircleClient<runtime.Types.Result.GetResult<Prisma.$CirclePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Circles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CircleCountArgs} args - Arguments to filter Circles to count.
   * @example
   * // Count the number of Circles
   * const count = await prisma.circle.count({
   *   where: {
   *     // ... the filter for the Circles we want to count
   *   }
   * })
  **/
  count<T extends CircleCountArgs>(
    args?: Prisma.Subset<T, CircleCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CircleCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Circle.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CircleAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CircleAggregateArgs>(args: Prisma.Subset<T, CircleAggregateArgs>): Prisma.PrismaPromise<GetCircleAggregateType<T>>

  /**
   * Group by Circle.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CircleGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CircleGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CircleGroupByArgs['orderBy'] }
      : { orderBy?: CircleGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CircleGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCircleGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Circle model
 */
readonly fields: CircleFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Circle.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CircleClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  works<T extends Prisma.Circle$worksArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Circle$worksArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorkPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Circle model
 */
export interface CircleFieldRefs {
  readonly id: Prisma.FieldRef<"Circle", 'String'>
  readonly name: Prisma.FieldRef<"Circle", 'String'>
}
    

// Custom InputTypes
/**
 * Circle findUnique
 */
export type CircleFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Circle
   */
  select?: Prisma.CircleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Circle
   */
  omit?: Prisma.CircleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CircleInclude<ExtArgs> | null
  /**
   * Filter, which Circle to fetch.
   */
  where: Prisma.CircleWhereUniqueInput
}

/**
 * Circle findUniqueOrThrow
 */
export type CircleFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Circle
   */
  select?: Prisma.CircleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Circle
   */
  omit?: Prisma.CircleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CircleInclude<ExtArgs> | null
  /**
   * Filter, which Circle to fetch.
   */
  where: Prisma.CircleWhereUniqueInput
}

/**
 * Circle findFirst
 */
export type CircleFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Circle
   */
  select?: Prisma.CircleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Circle
   */
  omit?: Prisma.CircleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CircleInclude<ExtArgs> | null
  /**
   * Filter, which Circle to fetch.
   */
  where?: Prisma.CircleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Circles to fetch.
   */
  orderBy?: Prisma.CircleOrderByWithRelationInput | Prisma.CircleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Circles.
   */
  cursor?: Prisma.CircleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Circles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Circles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Circles.
   */
  distinct?: Prisma.CircleScalarFieldEnum | Prisma.CircleScalarFieldEnum[]
}

/**
 * Circle findFirstOrThrow
 */
export type CircleFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Circle
   */
  select?: Prisma.CircleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Circle
   */
  omit?: Prisma.CircleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CircleInclude<ExtArgs> | null
  /**
   * Filter, which Circle to fetch.
   */
  where?: Prisma.CircleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Circles to fetch.
   */
  orderBy?: Prisma.CircleOrderByWithRelationInput | Prisma.CircleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Circles.
   */
  cursor?: Prisma.CircleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Circles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Circles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Circles.
   */
  distinct?: Prisma.CircleScalarFieldEnum | Prisma.CircleScalarFieldEnum[]
}

/**
 * Circle findMany
 */
export type CircleFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Circle
   */
  select?: Prisma.CircleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Circle
   */
  omit?: Prisma.CircleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CircleInclude<ExtArgs> | null
  /**
   * Filter, which Circles to fetch.
   */
  where?: Prisma.CircleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Circles to fetch.
   */
  orderBy?: Prisma.CircleOrderByWithRelationInput | Prisma.CircleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Circles.
   */
  cursor?: Prisma.CircleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Circles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Circles.
   */
  skip?: number
  distinct?: Prisma.CircleScalarFieldEnum | Prisma.CircleScalarFieldEnum[]
}

/**
 * Circle create
 */
export type CircleCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Circle
   */
  select?: Prisma.CircleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Circle
   */
  omit?: Prisma.CircleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CircleInclude<ExtArgs> | null
  /**
   * The data needed to create a Circle.
   */
  data: Prisma.XOR<Prisma.CircleCreateInput, Prisma.CircleUncheckedCreateInput>
}

/**
 * Circle createMany
 */
export type CircleCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Circles.
   */
  data: Prisma.CircleCreateManyInput | Prisma.CircleCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Circle createManyAndReturn
 */
export type CircleCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Circle
   */
  select?: Prisma.CircleSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Circle
   */
  omit?: Prisma.CircleOmit<ExtArgs> | null
  /**
   * The data used to create many Circles.
   */
  data: Prisma.CircleCreateManyInput | Prisma.CircleCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Circle update
 */
export type CircleUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Circle
   */
  select?: Prisma.CircleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Circle
   */
  omit?: Prisma.CircleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CircleInclude<ExtArgs> | null
  /**
   * The data needed to update a Circle.
   */
  data: Prisma.XOR<Prisma.CircleUpdateInput, Prisma.CircleUncheckedUpdateInput>
  /**
   * Choose, which Circle to update.
   */
  where: Prisma.CircleWhereUniqueInput
}

/**
 * Circle updateMany
 */
export type CircleUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Circles.
   */
  data: Prisma.XOR<Prisma.CircleUpdateManyMutationInput, Prisma.CircleUncheckedUpdateManyInput>
  /**
   * Filter which Circles to update
   */
  where?: Prisma.CircleWhereInput
  /**
   * Limit how many Circles to update.
   */
  limit?: number
}

/**
 * Circle updateManyAndReturn
 */
export type CircleUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Circle
   */
  select?: Prisma.CircleSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Circle
   */
  omit?: Prisma.CircleOmit<ExtArgs> | null
  /**
   * The data used to update Circles.
   */
  data: Prisma.XOR<Prisma.CircleUpdateManyMutationInput, Prisma.CircleUncheckedUpdateManyInput>
  /**
   * Filter which Circles to update
   */
  where?: Prisma.CircleWhereInput
  /**
   * Limit how many Circles to update.
   */
  limit?: number
}

/**
 * Circle upsert
 */
export type CircleUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Circle
   */
  select?: Prisma.CircleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Circle
   */
  omit?: Prisma.CircleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CircleInclude<ExtArgs> | null
  /**
   * The filter to search for the Circle to update in case it exists.
   */
  where: Prisma.CircleWhereUniqueInput
  /**
   * In case the Circle found by the `where` argument doesn't exist, create a new Circle with this data.
   */
  create: Prisma.XOR<Prisma.CircleCreateInput, Prisma.CircleUncheckedCreateInput>
  /**
   * In case the Circle was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CircleUpdateInput, Prisma.CircleUncheckedUpdateInput>
}

/**
 * Circle delete
 */
export type CircleDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Circle
   */
  select?: Prisma.CircleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Circle
   */
  omit?: Prisma.CircleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CircleInclude<ExtArgs> | null
  /**
   * Filter which Circle to delete.
   */
  where: Prisma.CircleWhereUniqueInput
}

/**
 * Circle deleteMany
 */
export type CircleDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Circles to delete
   */
  where?: Prisma.CircleWhereInput
  /**
   * Limit how many Circles to delete.
   */
  limit?: number
}

/**
 * Circle.works
 */
export type Circle$worksArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Work
   */
  select?: Prisma.WorkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Work
   */
  omit?: Prisma.WorkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkInclude<ExtArgs> | null
  where?: Prisma.WorkWhereInput
  orderBy?: Prisma.WorkOrderByWithRelationInput | Prisma.WorkOrderByWithRelationInput[]
  cursor?: Prisma.WorkWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.WorkScalarFieldEnum | Prisma.WorkScalarFieldEnum[]
}

/**
 * Circle without action
 */
export type CircleDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Circle
   */
  select?: Prisma.CircleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Circle
   */
  omit?: Prisma.CircleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CircleInclude<ExtArgs> | null
}
