
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Illustrator` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Illustrator
 * 
 */
export type IllustratorModel = runtime.Types.Result.DefaultSelection<Prisma.$IllustratorPayload>

export type AggregateIllustrator = {
  _count: IllustratorCountAggregateOutputType | null
  _avg: IllustratorAvgAggregateOutputType | null
  _sum: IllustratorSumAggregateOutputType | null
  _min: IllustratorMinAggregateOutputType | null
  _max: IllustratorMaxAggregateOutputType | null
}

export type IllustratorAvgAggregateOutputType = {
  id: number | null
}

export type IllustratorSumAggregateOutputType = {
  id: number | null
}

export type IllustratorMinAggregateOutputType = {
  id: number | null
  name: string | null
}

export type IllustratorMaxAggregateOutputType = {
  id: number | null
  name: string | null
}

export type IllustratorCountAggregateOutputType = {
  id: number
  name: number
  _all: number
}


export type IllustratorAvgAggregateInputType = {
  id?: true
}

export type IllustratorSumAggregateInputType = {
  id?: true
}

export type IllustratorMinAggregateInputType = {
  id?: true
  name?: true
}

export type IllustratorMaxAggregateInputType = {
  id?: true
  name?: true
}

export type IllustratorCountAggregateInputType = {
  id?: true
  name?: true
  _all?: true
}

export type IllustratorAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Illustrator to aggregate.
   */
  where?: Prisma.IllustratorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Illustrators to fetch.
   */
  orderBy?: Prisma.IllustratorOrderByWithRelationInput | Prisma.IllustratorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.IllustratorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Illustrators from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Illustrators.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Illustrators
  **/
  _count?: true | IllustratorCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: IllustratorAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: IllustratorSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: IllustratorMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: IllustratorMaxAggregateInputType
}

export type GetIllustratorAggregateType<T extends IllustratorAggregateArgs> = {
      [P in keyof T & keyof AggregateIllustrator]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateIllustrator[P]>
    : Prisma.GetScalarType<T[P], AggregateIllustrator[P]>
}




export type IllustratorGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.IllustratorWhereInput
  orderBy?: Prisma.IllustratorOrderByWithAggregationInput | Prisma.IllustratorOrderByWithAggregationInput[]
  by: Prisma.IllustratorScalarFieldEnum[] | Prisma.IllustratorScalarFieldEnum
  having?: Prisma.IllustratorScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: IllustratorCountAggregateInputType | true
  _avg?: IllustratorAvgAggregateInputType
  _sum?: IllustratorSumAggregateInputType
  _min?: IllustratorMinAggregateInputType
  _max?: IllustratorMaxAggregateInputType
}

export type IllustratorGroupByOutputType = {
  id: number
  name: string
  _count: IllustratorCountAggregateOutputType | null
  _avg: IllustratorAvgAggregateOutputType | null
  _sum: IllustratorSumAggregateOutputType | null
  _min: IllustratorMinAggregateOutputType | null
  _max: IllustratorMaxAggregateOutputType | null
}

type GetIllustratorGroupByPayload<T extends IllustratorGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<IllustratorGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof IllustratorGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], IllustratorGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], IllustratorGroupByOutputType[P]>
      }
    >
  >



export type IllustratorWhereInput = {
  AND?: Prisma.IllustratorWhereInput | Prisma.IllustratorWhereInput[]
  OR?: Prisma.IllustratorWhereInput[]
  NOT?: Prisma.IllustratorWhereInput | Prisma.IllustratorWhereInput[]
  id?: Prisma.IntFilter<"Illustrator"> | number
  name?: Prisma.StringFilter<"Illustrator"> | string
  works?: Prisma.WorkListRelationFilter
}

export type IllustratorOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  works?: Prisma.WorkOrderByRelationAggregateInput
}

export type IllustratorWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  name?: string
  AND?: Prisma.IllustratorWhereInput | Prisma.IllustratorWhereInput[]
  OR?: Prisma.IllustratorWhereInput[]
  NOT?: Prisma.IllustratorWhereInput | Prisma.IllustratorWhereInput[]
  works?: Prisma.WorkListRelationFilter
}, "id" | "name">

export type IllustratorOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  _count?: Prisma.IllustratorCountOrderByAggregateInput
  _avg?: Prisma.IllustratorAvgOrderByAggregateInput
  _max?: Prisma.IllustratorMaxOrderByAggregateInput
  _min?: Prisma.IllustratorMinOrderByAggregateInput
  _sum?: Prisma.IllustratorSumOrderByAggregateInput
}

export type IllustratorScalarWhereWithAggregatesInput = {
  AND?: Prisma.IllustratorScalarWhereWithAggregatesInput | Prisma.IllustratorScalarWhereWithAggregatesInput[]
  OR?: Prisma.IllustratorScalarWhereWithAggregatesInput[]
  NOT?: Prisma.IllustratorScalarWhereWithAggregatesInput | Prisma.IllustratorScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Illustrator"> | number
  name?: Prisma.StringWithAggregatesFilter<"Illustrator"> | string
}

export type IllustratorCreateInput = {
  name: string
  works?: Prisma.WorkCreateNestedManyWithoutIllustratorsInput
}

export type IllustratorUncheckedCreateInput = {
  id?: number
  name: string
  works?: Prisma.WorkUncheckedCreateNestedManyWithoutIllustratorsInput
}

export type IllustratorUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  works?: Prisma.WorkUpdateManyWithoutIllustratorsNestedInput
}

export type IllustratorUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  works?: Prisma.WorkUncheckedUpdateManyWithoutIllustratorsNestedInput
}

export type IllustratorCreateManyInput = {
  id?: number
  name: string
}

export type IllustratorUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type IllustratorUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type IllustratorListRelationFilter = {
  every?: Prisma.IllustratorWhereInput
  some?: Prisma.IllustratorWhereInput
  none?: Prisma.IllustratorWhereInput
}

export type IllustratorOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type IllustratorCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
}

export type IllustratorAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type IllustratorMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
}

export type IllustratorMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
}

export type IllustratorSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type IllustratorCreateNestedManyWithoutWorksInput = {
  create?: Prisma.XOR<Prisma.IllustratorCreateWithoutWorksInput, Prisma.IllustratorUncheckedCreateWithoutWorksInput> | Prisma.IllustratorCreateWithoutWorksInput[] | Prisma.IllustratorUncheckedCreateWithoutWorksInput[]
  connectOrCreate?: Prisma.IllustratorCreateOrConnectWithoutWorksInput | Prisma.IllustratorCreateOrConnectWithoutWorksInput[]
  connect?: Prisma.IllustratorWhereUniqueInput | Prisma.IllustratorWhereUniqueInput[]
}

export type IllustratorUncheckedCreateNestedManyWithoutWorksInput = {
  create?: Prisma.XOR<Prisma.IllustratorCreateWithoutWorksInput, Prisma.IllustratorUncheckedCreateWithoutWorksInput> | Prisma.IllustratorCreateWithoutWorksInput[] | Prisma.IllustratorUncheckedCreateWithoutWorksInput[]
  connectOrCreate?: Prisma.IllustratorCreateOrConnectWithoutWorksInput | Prisma.IllustratorCreateOrConnectWithoutWorksInput[]
  connect?: Prisma.IllustratorWhereUniqueInput | Prisma.IllustratorWhereUniqueInput[]
}

export type IllustratorUpdateManyWithoutWorksNestedInput = {
  create?: Prisma.XOR<Prisma.IllustratorCreateWithoutWorksInput, Prisma.IllustratorUncheckedCreateWithoutWorksInput> | Prisma.IllustratorCreateWithoutWorksInput[] | Prisma.IllustratorUncheckedCreateWithoutWorksInput[]
  connectOrCreate?: Prisma.IllustratorCreateOrConnectWithoutWorksInput | Prisma.IllustratorCreateOrConnectWithoutWorksInput[]
  upsert?: Prisma.IllustratorUpsertWithWhereUniqueWithoutWorksInput | Prisma.IllustratorUpsertWithWhereUniqueWithoutWorksInput[]
  set?: Prisma.IllustratorWhereUniqueInput | Prisma.IllustratorWhereUniqueInput[]
  disconnect?: Prisma.IllustratorWhereUniqueInput | Prisma.IllustratorWhereUniqueInput[]
  delete?: Prisma.IllustratorWhereUniqueInput | Prisma.IllustratorWhereUniqueInput[]
  connect?: Prisma.IllustratorWhereUniqueInput | Prisma.IllustratorWhereUniqueInput[]
  update?: Prisma.IllustratorUpdateWithWhereUniqueWithoutWorksInput | Prisma.IllustratorUpdateWithWhereUniqueWithoutWorksInput[]
  updateMany?: Prisma.IllustratorUpdateManyWithWhereWithoutWorksInput | Prisma.IllustratorUpdateManyWithWhereWithoutWorksInput[]
  deleteMany?: Prisma.IllustratorScalarWhereInput | Prisma.IllustratorScalarWhereInput[]
}

export type IllustratorUncheckedUpdateManyWithoutWorksNestedInput = {
  create?: Prisma.XOR<Prisma.IllustratorCreateWithoutWorksInput, Prisma.IllustratorUncheckedCreateWithoutWorksInput> | Prisma.IllustratorCreateWithoutWorksInput[] | Prisma.IllustratorUncheckedCreateWithoutWorksInput[]
  connectOrCreate?: Prisma.IllustratorCreateOrConnectWithoutWorksInput | Prisma.IllustratorCreateOrConnectWithoutWorksInput[]
  upsert?: Prisma.IllustratorUpsertWithWhereUniqueWithoutWorksInput | Prisma.IllustratorUpsertWithWhereUniqueWithoutWorksInput[]
  set?: Prisma.IllustratorWhereUniqueInput | Prisma.IllustratorWhereUniqueInput[]
  disconnect?: Prisma.IllustratorWhereUniqueInput | Prisma.IllustratorWhereUniqueInput[]
  delete?: Prisma.IllustratorWhereUniqueInput | Prisma.IllustratorWhereUniqueInput[]
  connect?: Prisma.IllustratorWhereUniqueInput | Prisma.IllustratorWhereUniqueInput[]
  update?: Prisma.IllustratorUpdateWithWhereUniqueWithoutWorksInput | Prisma.IllustratorUpdateWithWhereUniqueWithoutWorksInput[]
  updateMany?: Prisma.IllustratorUpdateManyWithWhereWithoutWorksInput | Prisma.IllustratorUpdateManyWithWhereWithoutWorksInput[]
  deleteMany?: Prisma.IllustratorScalarWhereInput | Prisma.IllustratorScalarWhereInput[]
}

export type IllustratorCreateWithoutWorksInput = {
  name: string
}

export type IllustratorUncheckedCreateWithoutWorksInput = {
  id?: number
  name: string
}

export type IllustratorCreateOrConnectWithoutWorksInput = {
  where: Prisma.IllustratorWhereUniqueInput
  create: Prisma.XOR<Prisma.IllustratorCreateWithoutWorksInput, Prisma.IllustratorUncheckedCreateWithoutWorksInput>
}

export type IllustratorUpsertWithWhereUniqueWithoutWorksInput = {
  where: Prisma.IllustratorWhereUniqueInput
  update: Prisma.XOR<Prisma.IllustratorUpdateWithoutWorksInput, Prisma.IllustratorUncheckedUpdateWithoutWorksInput>
  create: Prisma.XOR<Prisma.IllustratorCreateWithoutWorksInput, Prisma.IllustratorUncheckedCreateWithoutWorksInput>
}

export type IllustratorUpdateWithWhereUniqueWithoutWorksInput = {
  where: Prisma.IllustratorWhereUniqueInput
  data: Prisma.XOR<Prisma.IllustratorUpdateWithoutWorksInput, Prisma.IllustratorUncheckedUpdateWithoutWorksInput>
}

export type IllustratorUpdateManyWithWhereWithoutWorksInput = {
  where: Prisma.IllustratorScalarWhereInput
  data: Prisma.XOR<Prisma.IllustratorUpdateManyMutationInput, Prisma.IllustratorUncheckedUpdateManyWithoutWorksInput>
}

export type IllustratorScalarWhereInput = {
  AND?: Prisma.IllustratorScalarWhereInput | Prisma.IllustratorScalarWhereInput[]
  OR?: Prisma.IllustratorScalarWhereInput[]
  NOT?: Prisma.IllustratorScalarWhereInput | Prisma.IllustratorScalarWhereInput[]
  id?: Prisma.IntFilter<"Illustrator"> | number
  name?: Prisma.StringFilter<"Illustrator"> | string
}

export type IllustratorUpdateWithoutWorksInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type IllustratorUncheckedUpdateWithoutWorksInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type IllustratorUncheckedUpdateManyWithoutWorksInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type IllustratorCountOutputType
 */

export type IllustratorCountOutputType = {
  works: number
}

export type IllustratorCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  works?: boolean | IllustratorCountOutputTypeCountWorksArgs
}

/**
 * IllustratorCountOutputType without action
 */
export type IllustratorCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IllustratorCountOutputType
   */
  select?: Prisma.IllustratorCountOutputTypeSelect<ExtArgs> | null
}

/**
 * IllustratorCountOutputType without action
 */
export type IllustratorCountOutputTypeCountWorksArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.WorkWhereInput
}


export type IllustratorSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  works?: boolean | Prisma.Illustrator$worksArgs<ExtArgs>
  _count?: boolean | Prisma.IllustratorCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["illustrator"]>

export type IllustratorSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
}, ExtArgs["result"]["illustrator"]>

export type IllustratorSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
}, ExtArgs["result"]["illustrator"]>

export type IllustratorSelectScalar = {
  id?: boolean
  name?: boolean
}

export type IllustratorOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name", ExtArgs["result"]["illustrator"]>
export type IllustratorInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  works?: boolean | Prisma.Illustrator$worksArgs<ExtArgs>
  _count?: boolean | Prisma.IllustratorCountOutputTypeDefaultArgs<ExtArgs>
}
export type IllustratorIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type IllustratorIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $IllustratorPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Illustrator"
  objects: {
    works: Prisma.$WorkPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    name: string
  }, ExtArgs["result"]["illustrator"]>
  composites: {}
}

export type IllustratorGetPayload<S extends boolean | null | undefined | IllustratorDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$IllustratorPayload, S>

export type IllustratorCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<IllustratorFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: IllustratorCountAggregateInputType | true
  }

export interface IllustratorDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Illustrator'], meta: { name: 'Illustrator' } }
  /**
   * Find zero or one Illustrator that matches the filter.
   * @param {IllustratorFindUniqueArgs} args - Arguments to find a Illustrator
   * @example
   * // Get one Illustrator
   * const illustrator = await prisma.illustrator.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends IllustratorFindUniqueArgs>(args: Prisma.SelectSubset<T, IllustratorFindUniqueArgs<ExtArgs>>): Prisma.Prisma__IllustratorClient<runtime.Types.Result.GetResult<Prisma.$IllustratorPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Illustrator that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {IllustratorFindUniqueOrThrowArgs} args - Arguments to find a Illustrator
   * @example
   * // Get one Illustrator
   * const illustrator = await prisma.illustrator.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends IllustratorFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, IllustratorFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__IllustratorClient<runtime.Types.Result.GetResult<Prisma.$IllustratorPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Illustrator that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IllustratorFindFirstArgs} args - Arguments to find a Illustrator
   * @example
   * // Get one Illustrator
   * const illustrator = await prisma.illustrator.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends IllustratorFindFirstArgs>(args?: Prisma.SelectSubset<T, IllustratorFindFirstArgs<ExtArgs>>): Prisma.Prisma__IllustratorClient<runtime.Types.Result.GetResult<Prisma.$IllustratorPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Illustrator that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IllustratorFindFirstOrThrowArgs} args - Arguments to find a Illustrator
   * @example
   * // Get one Illustrator
   * const illustrator = await prisma.illustrator.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends IllustratorFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, IllustratorFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__IllustratorClient<runtime.Types.Result.GetResult<Prisma.$IllustratorPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Illustrators that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IllustratorFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Illustrators
   * const illustrators = await prisma.illustrator.findMany()
   * 
   * // Get first 10 Illustrators
   * const illustrators = await prisma.illustrator.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const illustratorWithIdOnly = await prisma.illustrator.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends IllustratorFindManyArgs>(args?: Prisma.SelectSubset<T, IllustratorFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$IllustratorPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Illustrator.
   * @param {IllustratorCreateArgs} args - Arguments to create a Illustrator.
   * @example
   * // Create one Illustrator
   * const Illustrator = await prisma.illustrator.create({
   *   data: {
   *     // ... data to create a Illustrator
   *   }
   * })
   * 
   */
  create<T extends IllustratorCreateArgs>(args: Prisma.SelectSubset<T, IllustratorCreateArgs<ExtArgs>>): Prisma.Prisma__IllustratorClient<runtime.Types.Result.GetResult<Prisma.$IllustratorPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Illustrators.
   * @param {IllustratorCreateManyArgs} args - Arguments to create many Illustrators.
   * @example
   * // Create many Illustrators
   * const illustrator = await prisma.illustrator.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends IllustratorCreateManyArgs>(args?: Prisma.SelectSubset<T, IllustratorCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Illustrators and returns the data saved in the database.
   * @param {IllustratorCreateManyAndReturnArgs} args - Arguments to create many Illustrators.
   * @example
   * // Create many Illustrators
   * const illustrator = await prisma.illustrator.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Illustrators and only return the `id`
   * const illustratorWithIdOnly = await prisma.illustrator.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends IllustratorCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, IllustratorCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$IllustratorPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Illustrator.
   * @param {IllustratorDeleteArgs} args - Arguments to delete one Illustrator.
   * @example
   * // Delete one Illustrator
   * const Illustrator = await prisma.illustrator.delete({
   *   where: {
   *     // ... filter to delete one Illustrator
   *   }
   * })
   * 
   */
  delete<T extends IllustratorDeleteArgs>(args: Prisma.SelectSubset<T, IllustratorDeleteArgs<ExtArgs>>): Prisma.Prisma__IllustratorClient<runtime.Types.Result.GetResult<Prisma.$IllustratorPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Illustrator.
   * @param {IllustratorUpdateArgs} args - Arguments to update one Illustrator.
   * @example
   * // Update one Illustrator
   * const illustrator = await prisma.illustrator.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends IllustratorUpdateArgs>(args: Prisma.SelectSubset<T, IllustratorUpdateArgs<ExtArgs>>): Prisma.Prisma__IllustratorClient<runtime.Types.Result.GetResult<Prisma.$IllustratorPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Illustrators.
   * @param {IllustratorDeleteManyArgs} args - Arguments to filter Illustrators to delete.
   * @example
   * // Delete a few Illustrators
   * const { count } = await prisma.illustrator.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends IllustratorDeleteManyArgs>(args?: Prisma.SelectSubset<T, IllustratorDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Illustrators.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IllustratorUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Illustrators
   * const illustrator = await prisma.illustrator.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends IllustratorUpdateManyArgs>(args: Prisma.SelectSubset<T, IllustratorUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Illustrators and returns the data updated in the database.
   * @param {IllustratorUpdateManyAndReturnArgs} args - Arguments to update many Illustrators.
   * @example
   * // Update many Illustrators
   * const illustrator = await prisma.illustrator.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Illustrators and only return the `id`
   * const illustratorWithIdOnly = await prisma.illustrator.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends IllustratorUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, IllustratorUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$IllustratorPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Illustrator.
   * @param {IllustratorUpsertArgs} args - Arguments to update or create a Illustrator.
   * @example
   * // Update or create a Illustrator
   * const illustrator = await prisma.illustrator.upsert({
   *   create: {
   *     // ... data to create a Illustrator
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Illustrator we want to update
   *   }
   * })
   */
  upsert<T extends IllustratorUpsertArgs>(args: Prisma.SelectSubset<T, IllustratorUpsertArgs<ExtArgs>>): Prisma.Prisma__IllustratorClient<runtime.Types.Result.GetResult<Prisma.$IllustratorPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Illustrators.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IllustratorCountArgs} args - Arguments to filter Illustrators to count.
   * @example
   * // Count the number of Illustrators
   * const count = await prisma.illustrator.count({
   *   where: {
   *     // ... the filter for the Illustrators we want to count
   *   }
   * })
  **/
  count<T extends IllustratorCountArgs>(
    args?: Prisma.Subset<T, IllustratorCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], IllustratorCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Illustrator.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IllustratorAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends IllustratorAggregateArgs>(args: Prisma.Subset<T, IllustratorAggregateArgs>): Prisma.PrismaPromise<GetIllustratorAggregateType<T>>

  /**
   * Group by Illustrator.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IllustratorGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends IllustratorGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: IllustratorGroupByArgs['orderBy'] }
      : { orderBy?: IllustratorGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, IllustratorGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetIllustratorGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Illustrator model
 */
readonly fields: IllustratorFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Illustrator.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__IllustratorClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  works<T extends Prisma.Illustrator$worksArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Illustrator$worksArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorkPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Illustrator model
 */
export interface IllustratorFieldRefs {
  readonly id: Prisma.FieldRef<"Illustrator", 'Int'>
  readonly name: Prisma.FieldRef<"Illustrator", 'String'>
}
    

// Custom InputTypes
/**
 * Illustrator findUnique
 */
export type IllustratorFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Illustrator
   */
  select?: Prisma.IllustratorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Illustrator
   */
  omit?: Prisma.IllustratorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IllustratorInclude<ExtArgs> | null
  /**
   * Filter, which Illustrator to fetch.
   */
  where: Prisma.IllustratorWhereUniqueInput
}

/**
 * Illustrator findUniqueOrThrow
 */
export type IllustratorFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Illustrator
   */
  select?: Prisma.IllustratorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Illustrator
   */
  omit?: Prisma.IllustratorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IllustratorInclude<ExtArgs> | null
  /**
   * Filter, which Illustrator to fetch.
   */
  where: Prisma.IllustratorWhereUniqueInput
}

/**
 * Illustrator findFirst
 */
export type IllustratorFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Illustrator
   */
  select?: Prisma.IllustratorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Illustrator
   */
  omit?: Prisma.IllustratorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IllustratorInclude<ExtArgs> | null
  /**
   * Filter, which Illustrator to fetch.
   */
  where?: Prisma.IllustratorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Illustrators to fetch.
   */
  orderBy?: Prisma.IllustratorOrderByWithRelationInput | Prisma.IllustratorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Illustrators.
   */
  cursor?: Prisma.IllustratorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Illustrators from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Illustrators.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Illustrators.
   */
  distinct?: Prisma.IllustratorScalarFieldEnum | Prisma.IllustratorScalarFieldEnum[]
}

/**
 * Illustrator findFirstOrThrow
 */
export type IllustratorFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Illustrator
   */
  select?: Prisma.IllustratorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Illustrator
   */
  omit?: Prisma.IllustratorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IllustratorInclude<ExtArgs> | null
  /**
   * Filter, which Illustrator to fetch.
   */
  where?: Prisma.IllustratorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Illustrators to fetch.
   */
  orderBy?: Prisma.IllustratorOrderByWithRelationInput | Prisma.IllustratorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Illustrators.
   */
  cursor?: Prisma.IllustratorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Illustrators from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Illustrators.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Illustrators.
   */
  distinct?: Prisma.IllustratorScalarFieldEnum | Prisma.IllustratorScalarFieldEnum[]
}

/**
 * Illustrator findMany
 */
export type IllustratorFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Illustrator
   */
  select?: Prisma.IllustratorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Illustrator
   */
  omit?: Prisma.IllustratorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IllustratorInclude<ExtArgs> | null
  /**
   * Filter, which Illustrators to fetch.
   */
  where?: Prisma.IllustratorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Illustrators to fetch.
   */
  orderBy?: Prisma.IllustratorOrderByWithRelationInput | Prisma.IllustratorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Illustrators.
   */
  cursor?: Prisma.IllustratorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Illustrators from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Illustrators.
   */
  skip?: number
  distinct?: Prisma.IllustratorScalarFieldEnum | Prisma.IllustratorScalarFieldEnum[]
}

/**
 * Illustrator create
 */
export type IllustratorCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Illustrator
   */
  select?: Prisma.IllustratorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Illustrator
   */
  omit?: Prisma.IllustratorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IllustratorInclude<ExtArgs> | null
  /**
   * The data needed to create a Illustrator.
   */
  data: Prisma.XOR<Prisma.IllustratorCreateInput, Prisma.IllustratorUncheckedCreateInput>
}

/**
 * Illustrator createMany
 */
export type IllustratorCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Illustrators.
   */
  data: Prisma.IllustratorCreateManyInput | Prisma.IllustratorCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Illustrator createManyAndReturn
 */
export type IllustratorCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Illustrator
   */
  select?: Prisma.IllustratorSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Illustrator
   */
  omit?: Prisma.IllustratorOmit<ExtArgs> | null
  /**
   * The data used to create many Illustrators.
   */
  data: Prisma.IllustratorCreateManyInput | Prisma.IllustratorCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Illustrator update
 */
export type IllustratorUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Illustrator
   */
  select?: Prisma.IllustratorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Illustrator
   */
  omit?: Prisma.IllustratorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IllustratorInclude<ExtArgs> | null
  /**
   * The data needed to update a Illustrator.
   */
  data: Prisma.XOR<Prisma.IllustratorUpdateInput, Prisma.IllustratorUncheckedUpdateInput>
  /**
   * Choose, which Illustrator to update.
   */
  where: Prisma.IllustratorWhereUniqueInput
}

/**
 * Illustrator updateMany
 */
export type IllustratorUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Illustrators.
   */
  data: Prisma.XOR<Prisma.IllustratorUpdateManyMutationInput, Prisma.IllustratorUncheckedUpdateManyInput>
  /**
   * Filter which Illustrators to update
   */
  where?: Prisma.IllustratorWhereInput
  /**
   * Limit how many Illustrators to update.
   */
  limit?: number
}

/**
 * Illustrator updateManyAndReturn
 */
export type IllustratorUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Illustrator
   */
  select?: Prisma.IllustratorSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Illustrator
   */
  omit?: Prisma.IllustratorOmit<ExtArgs> | null
  /**
   * The data used to update Illustrators.
   */
  data: Prisma.XOR<Prisma.IllustratorUpdateManyMutationInput, Prisma.IllustratorUncheckedUpdateManyInput>
  /**
   * Filter which Illustrators to update
   */
  where?: Prisma.IllustratorWhereInput
  /**
   * Limit how many Illustrators to update.
   */
  limit?: number
}

/**
 * Illustrator upsert
 */
export type IllustratorUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Illustrator
   */
  select?: Prisma.IllustratorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Illustrator
   */
  omit?: Prisma.IllustratorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IllustratorInclude<ExtArgs> | null
  /**
   * The filter to search for the Illustrator to update in case it exists.
   */
  where: Prisma.IllustratorWhereUniqueInput
  /**
   * In case the Illustrator found by the `where` argument doesn't exist, create a new Illustrator with this data.
   */
  create: Prisma.XOR<Prisma.IllustratorCreateInput, Prisma.IllustratorUncheckedCreateInput>
  /**
   * In case the Illustrator was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.IllustratorUpdateInput, Prisma.IllustratorUncheckedUpdateInput>
}

/**
 * Illustrator delete
 */
export type IllustratorDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Illustrator
   */
  select?: Prisma.IllustratorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Illustrator
   */
  omit?: Prisma.IllustratorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IllustratorInclude<ExtArgs> | null
  /**
   * Filter which Illustrator to delete.
   */
  where: Prisma.IllustratorWhereUniqueInput
}

/**
 * Illustrator deleteMany
 */
export type IllustratorDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Illustrators to delete
   */
  where?: Prisma.IllustratorWhereInput
  /**
   * Limit how many Illustrators to delete.
   */
  limit?: number
}

/**
 * Illustrator.works
 */
export type Illustrator$worksArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Work
   */
  select?: Prisma.WorkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Work
   */
  omit?: Prisma.WorkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkInclude<ExtArgs> | null
  where?: Prisma.WorkWhereInput
  orderBy?: Prisma.WorkOrderByWithRelationInput | Prisma.WorkOrderByWithRelationInput[]
  cursor?: Prisma.WorkWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.WorkScalarFieldEnum | Prisma.WorkScalarFieldEnum[]
}

/**
 * Illustrator without action
 */
export type IllustratorDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Illustrator
   */
  select?: Prisma.IllustratorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Illustrator
   */
  omit?: Prisma.IllustratorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IllustratorInclude<ExtArgs> | null
}
