
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PlaylistWork` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model PlaylistWork
 * 
 */
export type PlaylistWorkModel = runtime.Types.Result.DefaultSelection<Prisma.$PlaylistWorkPayload>

export type AggregatePlaylistWork = {
  _count: PlaylistWorkCountAggregateOutputType | null
  _min: PlaylistWorkMinAggregateOutputType | null
  _max: PlaylistWorkMaxAggregateOutputType | null
}

export type PlaylistWorkMinAggregateOutputType = {
  playlistId: string | null
  workId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PlaylistWorkMaxAggregateOutputType = {
  playlistId: string | null
  workId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PlaylistWorkCountAggregateOutputType = {
  playlistId: number
  workId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type PlaylistWorkMinAggregateInputType = {
  playlistId?: true
  workId?: true
  createdAt?: true
  updatedAt?: true
}

export type PlaylistWorkMaxAggregateInputType = {
  playlistId?: true
  workId?: true
  createdAt?: true
  updatedAt?: true
}

export type PlaylistWorkCountAggregateInputType = {
  playlistId?: true
  workId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type PlaylistWorkAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PlaylistWork to aggregate.
   */
  where?: Prisma.PlaylistWorkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PlaylistWorks to fetch.
   */
  orderBy?: Prisma.PlaylistWorkOrderByWithRelationInput | Prisma.PlaylistWorkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PlaylistWorkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PlaylistWorks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PlaylistWorks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PlaylistWorks
  **/
  _count?: true | PlaylistWorkCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PlaylistWorkMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PlaylistWorkMaxAggregateInputType
}

export type GetPlaylistWorkAggregateType<T extends PlaylistWorkAggregateArgs> = {
      [P in keyof T & keyof AggregatePlaylistWork]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePlaylistWork[P]>
    : Prisma.GetScalarType<T[P], AggregatePlaylistWork[P]>
}




export type PlaylistWorkGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PlaylistWorkWhereInput
  orderBy?: Prisma.PlaylistWorkOrderByWithAggregationInput | Prisma.PlaylistWorkOrderByWithAggregationInput[]
  by: Prisma.PlaylistWorkScalarFieldEnum[] | Prisma.PlaylistWorkScalarFieldEnum
  having?: Prisma.PlaylistWorkScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PlaylistWorkCountAggregateInputType | true
  _min?: PlaylistWorkMinAggregateInputType
  _max?: PlaylistWorkMaxAggregateInputType
}

export type PlaylistWorkGroupByOutputType = {
  playlistId: string
  workId: string
  createdAt: Date
  updatedAt: Date
  _count: PlaylistWorkCountAggregateOutputType | null
  _min: PlaylistWorkMinAggregateOutputType | null
  _max: PlaylistWorkMaxAggregateOutputType | null
}

export type GetPlaylistWorkGroupByPayload<T extends PlaylistWorkGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PlaylistWorkGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PlaylistWorkGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PlaylistWorkGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PlaylistWorkGroupByOutputType[P]>
      }
    >
  >



export type PlaylistWorkWhereInput = {
  AND?: Prisma.PlaylistWorkWhereInput | Prisma.PlaylistWorkWhereInput[]
  OR?: Prisma.PlaylistWorkWhereInput[]
  NOT?: Prisma.PlaylistWorkWhereInput | Prisma.PlaylistWorkWhereInput[]
  playlistId?: Prisma.UuidFilter<"PlaylistWork"> | string
  workId?: Prisma.StringFilter<"PlaylistWork"> | string
  createdAt?: Prisma.DateTimeFilter<"PlaylistWork"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PlaylistWork"> | Date | string
  playlist?: Prisma.XOR<Prisma.PlaylistScalarRelationFilter, Prisma.PlaylistWhereInput>
  work?: Prisma.XOR<Prisma.WorkScalarRelationFilter, Prisma.WorkWhereInput>
}

export type PlaylistWorkOrderByWithRelationInput = {
  playlistId?: Prisma.SortOrder
  workId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  playlist?: Prisma.PlaylistOrderByWithRelationInput
  work?: Prisma.WorkOrderByWithRelationInput
}

export type PlaylistWorkWhereUniqueInput = Prisma.AtLeast<{
  playlistId_workId?: Prisma.PlaylistWorkPlaylistIdWorkIdCompoundUniqueInput
  AND?: Prisma.PlaylistWorkWhereInput | Prisma.PlaylistWorkWhereInput[]
  OR?: Prisma.PlaylistWorkWhereInput[]
  NOT?: Prisma.PlaylistWorkWhereInput | Prisma.PlaylistWorkWhereInput[]
  playlistId?: Prisma.UuidFilter<"PlaylistWork"> | string
  workId?: Prisma.StringFilter<"PlaylistWork"> | string
  createdAt?: Prisma.DateTimeFilter<"PlaylistWork"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PlaylistWork"> | Date | string
  playlist?: Prisma.XOR<Prisma.PlaylistScalarRelationFilter, Prisma.PlaylistWhereInput>
  work?: Prisma.XOR<Prisma.WorkScalarRelationFilter, Prisma.WorkWhereInput>
}, "playlistId_workId">

export type PlaylistWorkOrderByWithAggregationInput = {
  playlistId?: Prisma.SortOrder
  workId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.PlaylistWorkCountOrderByAggregateInput
  _max?: Prisma.PlaylistWorkMaxOrderByAggregateInput
  _min?: Prisma.PlaylistWorkMinOrderByAggregateInput
}

export type PlaylistWorkScalarWhereWithAggregatesInput = {
  AND?: Prisma.PlaylistWorkScalarWhereWithAggregatesInput | Prisma.PlaylistWorkScalarWhereWithAggregatesInput[]
  OR?: Prisma.PlaylistWorkScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PlaylistWorkScalarWhereWithAggregatesInput | Prisma.PlaylistWorkScalarWhereWithAggregatesInput[]
  playlistId?: Prisma.UuidWithAggregatesFilter<"PlaylistWork"> | string
  workId?: Prisma.StringWithAggregatesFilter<"PlaylistWork"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"PlaylistWork"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"PlaylistWork"> | Date | string
}

export type PlaylistWorkCreateInput = {
  createdAt?: Date | string
  updatedAt?: Date | string
  playlist: Prisma.PlaylistCreateNestedOneWithoutWorksInput
  work: Prisma.WorkCreateNestedOneWithoutPlaylistWorksInput
}

export type PlaylistWorkUncheckedCreateInput = {
  playlistId: string
  workId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PlaylistWorkUpdateInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  playlist?: Prisma.PlaylistUpdateOneRequiredWithoutWorksNestedInput
  work?: Prisma.WorkUpdateOneRequiredWithoutPlaylistWorksNestedInput
}

export type PlaylistWorkUncheckedUpdateInput = {
  playlistId?: Prisma.StringFieldUpdateOperationsInput | string
  workId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PlaylistWorkCreateManyInput = {
  playlistId: string
  workId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PlaylistWorkUpdateManyMutationInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PlaylistWorkUncheckedUpdateManyInput = {
  playlistId?: Prisma.StringFieldUpdateOperationsInput | string
  workId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PlaylistWorkListRelationFilter = {
  every?: Prisma.PlaylistWorkWhereInput
  some?: Prisma.PlaylistWorkWhereInput
  none?: Prisma.PlaylistWorkWhereInput
}

export type PlaylistWorkOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PlaylistWorkPlaylistIdWorkIdCompoundUniqueInput = {
  playlistId: string
  workId: string
}

export type PlaylistWorkCountOrderByAggregateInput = {
  playlistId?: Prisma.SortOrder
  workId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PlaylistWorkMaxOrderByAggregateInput = {
  playlistId?: Prisma.SortOrder
  workId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PlaylistWorkMinOrderByAggregateInput = {
  playlistId?: Prisma.SortOrder
  workId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PlaylistWorkCreateNestedManyWithoutWorkInput = {
  create?: Prisma.XOR<Prisma.PlaylistWorkCreateWithoutWorkInput, Prisma.PlaylistWorkUncheckedCreateWithoutWorkInput> | Prisma.PlaylistWorkCreateWithoutWorkInput[] | Prisma.PlaylistWorkUncheckedCreateWithoutWorkInput[]
  connectOrCreate?: Prisma.PlaylistWorkCreateOrConnectWithoutWorkInput | Prisma.PlaylistWorkCreateOrConnectWithoutWorkInput[]
  createMany?: Prisma.PlaylistWorkCreateManyWorkInputEnvelope
  connect?: Prisma.PlaylistWorkWhereUniqueInput | Prisma.PlaylistWorkWhereUniqueInput[]
}

export type PlaylistWorkUncheckedCreateNestedManyWithoutWorkInput = {
  create?: Prisma.XOR<Prisma.PlaylistWorkCreateWithoutWorkInput, Prisma.PlaylistWorkUncheckedCreateWithoutWorkInput> | Prisma.PlaylistWorkCreateWithoutWorkInput[] | Prisma.PlaylistWorkUncheckedCreateWithoutWorkInput[]
  connectOrCreate?: Prisma.PlaylistWorkCreateOrConnectWithoutWorkInput | Prisma.PlaylistWorkCreateOrConnectWithoutWorkInput[]
  createMany?: Prisma.PlaylistWorkCreateManyWorkInputEnvelope
  connect?: Prisma.PlaylistWorkWhereUniqueInput | Prisma.PlaylistWorkWhereUniqueInput[]
}

export type PlaylistWorkUpdateManyWithoutWorkNestedInput = {
  create?: Prisma.XOR<Prisma.PlaylistWorkCreateWithoutWorkInput, Prisma.PlaylistWorkUncheckedCreateWithoutWorkInput> | Prisma.PlaylistWorkCreateWithoutWorkInput[] | Prisma.PlaylistWorkUncheckedCreateWithoutWorkInput[]
  connectOrCreate?: Prisma.PlaylistWorkCreateOrConnectWithoutWorkInput | Prisma.PlaylistWorkCreateOrConnectWithoutWorkInput[]
  upsert?: Prisma.PlaylistWorkUpsertWithWhereUniqueWithoutWorkInput | Prisma.PlaylistWorkUpsertWithWhereUniqueWithoutWorkInput[]
  createMany?: Prisma.PlaylistWorkCreateManyWorkInputEnvelope
  set?: Prisma.PlaylistWorkWhereUniqueInput | Prisma.PlaylistWorkWhereUniqueInput[]
  disconnect?: Prisma.PlaylistWorkWhereUniqueInput | Prisma.PlaylistWorkWhereUniqueInput[]
  delete?: Prisma.PlaylistWorkWhereUniqueInput | Prisma.PlaylistWorkWhereUniqueInput[]
  connect?: Prisma.PlaylistWorkWhereUniqueInput | Prisma.PlaylistWorkWhereUniqueInput[]
  update?: Prisma.PlaylistWorkUpdateWithWhereUniqueWithoutWorkInput | Prisma.PlaylistWorkUpdateWithWhereUniqueWithoutWorkInput[]
  updateMany?: Prisma.PlaylistWorkUpdateManyWithWhereWithoutWorkInput | Prisma.PlaylistWorkUpdateManyWithWhereWithoutWorkInput[]
  deleteMany?: Prisma.PlaylistWorkScalarWhereInput | Prisma.PlaylistWorkScalarWhereInput[]
}

export type PlaylistWorkUncheckedUpdateManyWithoutWorkNestedInput = {
  create?: Prisma.XOR<Prisma.PlaylistWorkCreateWithoutWorkInput, Prisma.PlaylistWorkUncheckedCreateWithoutWorkInput> | Prisma.PlaylistWorkCreateWithoutWorkInput[] | Prisma.PlaylistWorkUncheckedCreateWithoutWorkInput[]
  connectOrCreate?: Prisma.PlaylistWorkCreateOrConnectWithoutWorkInput | Prisma.PlaylistWorkCreateOrConnectWithoutWorkInput[]
  upsert?: Prisma.PlaylistWorkUpsertWithWhereUniqueWithoutWorkInput | Prisma.PlaylistWorkUpsertWithWhereUniqueWithoutWorkInput[]
  createMany?: Prisma.PlaylistWorkCreateManyWorkInputEnvelope
  set?: Prisma.PlaylistWorkWhereUniqueInput | Prisma.PlaylistWorkWhereUniqueInput[]
  disconnect?: Prisma.PlaylistWorkWhereUniqueInput | Prisma.PlaylistWorkWhereUniqueInput[]
  delete?: Prisma.PlaylistWorkWhereUniqueInput | Prisma.PlaylistWorkWhereUniqueInput[]
  connect?: Prisma.PlaylistWorkWhereUniqueInput | Prisma.PlaylistWorkWhereUniqueInput[]
  update?: Prisma.PlaylistWorkUpdateWithWhereUniqueWithoutWorkInput | Prisma.PlaylistWorkUpdateWithWhereUniqueWithoutWorkInput[]
  updateMany?: Prisma.PlaylistWorkUpdateManyWithWhereWithoutWorkInput | Prisma.PlaylistWorkUpdateManyWithWhereWithoutWorkInput[]
  deleteMany?: Prisma.PlaylistWorkScalarWhereInput | Prisma.PlaylistWorkScalarWhereInput[]
}

export type PlaylistWorkCreateNestedManyWithoutPlaylistInput = {
  create?: Prisma.XOR<Prisma.PlaylistWorkCreateWithoutPlaylistInput, Prisma.PlaylistWorkUncheckedCreateWithoutPlaylistInput> | Prisma.PlaylistWorkCreateWithoutPlaylistInput[] | Prisma.PlaylistWorkUncheckedCreateWithoutPlaylistInput[]
  connectOrCreate?: Prisma.PlaylistWorkCreateOrConnectWithoutPlaylistInput | Prisma.PlaylistWorkCreateOrConnectWithoutPlaylistInput[]
  createMany?: Prisma.PlaylistWorkCreateManyPlaylistInputEnvelope
  connect?: Prisma.PlaylistWorkWhereUniqueInput | Prisma.PlaylistWorkWhereUniqueInput[]
}

export type PlaylistWorkUncheckedCreateNestedManyWithoutPlaylistInput = {
  create?: Prisma.XOR<Prisma.PlaylistWorkCreateWithoutPlaylistInput, Prisma.PlaylistWorkUncheckedCreateWithoutPlaylistInput> | Prisma.PlaylistWorkCreateWithoutPlaylistInput[] | Prisma.PlaylistWorkUncheckedCreateWithoutPlaylistInput[]
  connectOrCreate?: Prisma.PlaylistWorkCreateOrConnectWithoutPlaylistInput | Prisma.PlaylistWorkCreateOrConnectWithoutPlaylistInput[]
  createMany?: Prisma.PlaylistWorkCreateManyPlaylistInputEnvelope
  connect?: Prisma.PlaylistWorkWhereUniqueInput | Prisma.PlaylistWorkWhereUniqueInput[]
}

export type PlaylistWorkUpdateManyWithoutPlaylistNestedInput = {
  create?: Prisma.XOR<Prisma.PlaylistWorkCreateWithoutPlaylistInput, Prisma.PlaylistWorkUncheckedCreateWithoutPlaylistInput> | Prisma.PlaylistWorkCreateWithoutPlaylistInput[] | Prisma.PlaylistWorkUncheckedCreateWithoutPlaylistInput[]
  connectOrCreate?: Prisma.PlaylistWorkCreateOrConnectWithoutPlaylistInput | Prisma.PlaylistWorkCreateOrConnectWithoutPlaylistInput[]
  upsert?: Prisma.PlaylistWorkUpsertWithWhereUniqueWithoutPlaylistInput | Prisma.PlaylistWorkUpsertWithWhereUniqueWithoutPlaylistInput[]
  createMany?: Prisma.PlaylistWorkCreateManyPlaylistInputEnvelope
  set?: Prisma.PlaylistWorkWhereUniqueInput | Prisma.PlaylistWorkWhereUniqueInput[]
  disconnect?: Prisma.PlaylistWorkWhereUniqueInput | Prisma.PlaylistWorkWhereUniqueInput[]
  delete?: Prisma.PlaylistWorkWhereUniqueInput | Prisma.PlaylistWorkWhereUniqueInput[]
  connect?: Prisma.PlaylistWorkWhereUniqueInput | Prisma.PlaylistWorkWhereUniqueInput[]
  update?: Prisma.PlaylistWorkUpdateWithWhereUniqueWithoutPlaylistInput | Prisma.PlaylistWorkUpdateWithWhereUniqueWithoutPlaylistInput[]
  updateMany?: Prisma.PlaylistWorkUpdateManyWithWhereWithoutPlaylistInput | Prisma.PlaylistWorkUpdateManyWithWhereWithoutPlaylistInput[]
  deleteMany?: Prisma.PlaylistWorkScalarWhereInput | Prisma.PlaylistWorkScalarWhereInput[]
}

export type PlaylistWorkUncheckedUpdateManyWithoutPlaylistNestedInput = {
  create?: Prisma.XOR<Prisma.PlaylistWorkCreateWithoutPlaylistInput, Prisma.PlaylistWorkUncheckedCreateWithoutPlaylistInput> | Prisma.PlaylistWorkCreateWithoutPlaylistInput[] | Prisma.PlaylistWorkUncheckedCreateWithoutPlaylistInput[]
  connectOrCreate?: Prisma.PlaylistWorkCreateOrConnectWithoutPlaylistInput | Prisma.PlaylistWorkCreateOrConnectWithoutPlaylistInput[]
  upsert?: Prisma.PlaylistWorkUpsertWithWhereUniqueWithoutPlaylistInput | Prisma.PlaylistWorkUpsertWithWhereUniqueWithoutPlaylistInput[]
  createMany?: Prisma.PlaylistWorkCreateManyPlaylistInputEnvelope
  set?: Prisma.PlaylistWorkWhereUniqueInput | Prisma.PlaylistWorkWhereUniqueInput[]
  disconnect?: Prisma.PlaylistWorkWhereUniqueInput | Prisma.PlaylistWorkWhereUniqueInput[]
  delete?: Prisma.PlaylistWorkWhereUniqueInput | Prisma.PlaylistWorkWhereUniqueInput[]
  connect?: Prisma.PlaylistWorkWhereUniqueInput | Prisma.PlaylistWorkWhereUniqueInput[]
  update?: Prisma.PlaylistWorkUpdateWithWhereUniqueWithoutPlaylistInput | Prisma.PlaylistWorkUpdateWithWhereUniqueWithoutPlaylistInput[]
  updateMany?: Prisma.PlaylistWorkUpdateManyWithWhereWithoutPlaylistInput | Prisma.PlaylistWorkUpdateManyWithWhereWithoutPlaylistInput[]
  deleteMany?: Prisma.PlaylistWorkScalarWhereInput | Prisma.PlaylistWorkScalarWhereInput[]
}

export type PlaylistWorkCreateWithoutWorkInput = {
  createdAt?: Date | string
  updatedAt?: Date | string
  playlist: Prisma.PlaylistCreateNestedOneWithoutWorksInput
}

export type PlaylistWorkUncheckedCreateWithoutWorkInput = {
  playlistId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PlaylistWorkCreateOrConnectWithoutWorkInput = {
  where: Prisma.PlaylistWorkWhereUniqueInput
  create: Prisma.XOR<Prisma.PlaylistWorkCreateWithoutWorkInput, Prisma.PlaylistWorkUncheckedCreateWithoutWorkInput>
}

export type PlaylistWorkCreateManyWorkInputEnvelope = {
  data: Prisma.PlaylistWorkCreateManyWorkInput | Prisma.PlaylistWorkCreateManyWorkInput[]
  skipDuplicates?: boolean
}

export type PlaylistWorkUpsertWithWhereUniqueWithoutWorkInput = {
  where: Prisma.PlaylistWorkWhereUniqueInput
  update: Prisma.XOR<Prisma.PlaylistWorkUpdateWithoutWorkInput, Prisma.PlaylistWorkUncheckedUpdateWithoutWorkInput>
  create: Prisma.XOR<Prisma.PlaylistWorkCreateWithoutWorkInput, Prisma.PlaylistWorkUncheckedCreateWithoutWorkInput>
}

export type PlaylistWorkUpdateWithWhereUniqueWithoutWorkInput = {
  where: Prisma.PlaylistWorkWhereUniqueInput
  data: Prisma.XOR<Prisma.PlaylistWorkUpdateWithoutWorkInput, Prisma.PlaylistWorkUncheckedUpdateWithoutWorkInput>
}

export type PlaylistWorkUpdateManyWithWhereWithoutWorkInput = {
  where: Prisma.PlaylistWorkScalarWhereInput
  data: Prisma.XOR<Prisma.PlaylistWorkUpdateManyMutationInput, Prisma.PlaylistWorkUncheckedUpdateManyWithoutWorkInput>
}

export type PlaylistWorkScalarWhereInput = {
  AND?: Prisma.PlaylistWorkScalarWhereInput | Prisma.PlaylistWorkScalarWhereInput[]
  OR?: Prisma.PlaylistWorkScalarWhereInput[]
  NOT?: Prisma.PlaylistWorkScalarWhereInput | Prisma.PlaylistWorkScalarWhereInput[]
  playlistId?: Prisma.UuidFilter<"PlaylistWork"> | string
  workId?: Prisma.StringFilter<"PlaylistWork"> | string
  createdAt?: Prisma.DateTimeFilter<"PlaylistWork"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PlaylistWork"> | Date | string
}

export type PlaylistWorkCreateWithoutPlaylistInput = {
  createdAt?: Date | string
  updatedAt?: Date | string
  work: Prisma.WorkCreateNestedOneWithoutPlaylistWorksInput
}

export type PlaylistWorkUncheckedCreateWithoutPlaylistInput = {
  workId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PlaylistWorkCreateOrConnectWithoutPlaylistInput = {
  where: Prisma.PlaylistWorkWhereUniqueInput
  create: Prisma.XOR<Prisma.PlaylistWorkCreateWithoutPlaylistInput, Prisma.PlaylistWorkUncheckedCreateWithoutPlaylistInput>
}

export type PlaylistWorkCreateManyPlaylistInputEnvelope = {
  data: Prisma.PlaylistWorkCreateManyPlaylistInput | Prisma.PlaylistWorkCreateManyPlaylistInput[]
  skipDuplicates?: boolean
}

export type PlaylistWorkUpsertWithWhereUniqueWithoutPlaylistInput = {
  where: Prisma.PlaylistWorkWhereUniqueInput
  update: Prisma.XOR<Prisma.PlaylistWorkUpdateWithoutPlaylistInput, Prisma.PlaylistWorkUncheckedUpdateWithoutPlaylistInput>
  create: Prisma.XOR<Prisma.PlaylistWorkCreateWithoutPlaylistInput, Prisma.PlaylistWorkUncheckedCreateWithoutPlaylistInput>
}

export type PlaylistWorkUpdateWithWhereUniqueWithoutPlaylistInput = {
  where: Prisma.PlaylistWorkWhereUniqueInput
  data: Prisma.XOR<Prisma.PlaylistWorkUpdateWithoutPlaylistInput, Prisma.PlaylistWorkUncheckedUpdateWithoutPlaylistInput>
}

export type PlaylistWorkUpdateManyWithWhereWithoutPlaylistInput = {
  where: Prisma.PlaylistWorkScalarWhereInput
  data: Prisma.XOR<Prisma.PlaylistWorkUpdateManyMutationInput, Prisma.PlaylistWorkUncheckedUpdateManyWithoutPlaylistInput>
}

export type PlaylistWorkCreateManyWorkInput = {
  playlistId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PlaylistWorkUpdateWithoutWorkInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  playlist?: Prisma.PlaylistUpdateOneRequiredWithoutWorksNestedInput
}

export type PlaylistWorkUncheckedUpdateWithoutWorkInput = {
  playlistId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PlaylistWorkUncheckedUpdateManyWithoutWorkInput = {
  playlistId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PlaylistWorkCreateManyPlaylistInput = {
  workId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PlaylistWorkUpdateWithoutPlaylistInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  work?: Prisma.WorkUpdateOneRequiredWithoutPlaylistWorksNestedInput
}

export type PlaylistWorkUncheckedUpdateWithoutPlaylistInput = {
  workId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PlaylistWorkUncheckedUpdateManyWithoutPlaylistInput = {
  workId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type PlaylistWorkSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  playlistId?: boolean
  workId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  playlist?: boolean | Prisma.PlaylistDefaultArgs<ExtArgs>
  work?: boolean | Prisma.WorkDefaultArgs<ExtArgs>
}, ExtArgs["result"]["playlistWork"]>

export type PlaylistWorkSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  playlistId?: boolean
  workId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  playlist?: boolean | Prisma.PlaylistDefaultArgs<ExtArgs>
  work?: boolean | Prisma.WorkDefaultArgs<ExtArgs>
}, ExtArgs["result"]["playlistWork"]>

export type PlaylistWorkSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  playlistId?: boolean
  workId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  playlist?: boolean | Prisma.PlaylistDefaultArgs<ExtArgs>
  work?: boolean | Prisma.WorkDefaultArgs<ExtArgs>
}, ExtArgs["result"]["playlistWork"]>

export type PlaylistWorkSelectScalar = {
  playlistId?: boolean
  workId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type PlaylistWorkOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"playlistId" | "workId" | "createdAt" | "updatedAt", ExtArgs["result"]["playlistWork"]>
export type PlaylistWorkInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  playlist?: boolean | Prisma.PlaylistDefaultArgs<ExtArgs>
  work?: boolean | Prisma.WorkDefaultArgs<ExtArgs>
}
export type PlaylistWorkIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  playlist?: boolean | Prisma.PlaylistDefaultArgs<ExtArgs>
  work?: boolean | Prisma.WorkDefaultArgs<ExtArgs>
}
export type PlaylistWorkIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  playlist?: boolean | Prisma.PlaylistDefaultArgs<ExtArgs>
  work?: boolean | Prisma.WorkDefaultArgs<ExtArgs>
}

export type $PlaylistWorkPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PlaylistWork"
  objects: {
    playlist: Prisma.$PlaylistPayload<ExtArgs>
    work: Prisma.$WorkPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    playlistId: string
    workId: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["playlistWork"]>
  composites: {}
}

export type PlaylistWorkGetPayload<S extends boolean | null | undefined | PlaylistWorkDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PlaylistWorkPayload, S>

export type PlaylistWorkCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PlaylistWorkFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PlaylistWorkCountAggregateInputType | true
  }

export interface PlaylistWorkDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PlaylistWork'], meta: { name: 'PlaylistWork' } }
  /**
   * Find zero or one PlaylistWork that matches the filter.
   * @param {PlaylistWorkFindUniqueArgs} args - Arguments to find a PlaylistWork
   * @example
   * // Get one PlaylistWork
   * const playlistWork = await prisma.playlistWork.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PlaylistWorkFindUniqueArgs>(args: Prisma.SelectSubset<T, PlaylistWorkFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PlaylistWorkClient<runtime.Types.Result.GetResult<Prisma.$PlaylistWorkPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PlaylistWork that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PlaylistWorkFindUniqueOrThrowArgs} args - Arguments to find a PlaylistWork
   * @example
   * // Get one PlaylistWork
   * const playlistWork = await prisma.playlistWork.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PlaylistWorkFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PlaylistWorkFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PlaylistWorkClient<runtime.Types.Result.GetResult<Prisma.$PlaylistWorkPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PlaylistWork that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaylistWorkFindFirstArgs} args - Arguments to find a PlaylistWork
   * @example
   * // Get one PlaylistWork
   * const playlistWork = await prisma.playlistWork.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PlaylistWorkFindFirstArgs>(args?: Prisma.SelectSubset<T, PlaylistWorkFindFirstArgs<ExtArgs>>): Prisma.Prisma__PlaylistWorkClient<runtime.Types.Result.GetResult<Prisma.$PlaylistWorkPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PlaylistWork that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaylistWorkFindFirstOrThrowArgs} args - Arguments to find a PlaylistWork
   * @example
   * // Get one PlaylistWork
   * const playlistWork = await prisma.playlistWork.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PlaylistWorkFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PlaylistWorkFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PlaylistWorkClient<runtime.Types.Result.GetResult<Prisma.$PlaylistWorkPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PlaylistWorks that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaylistWorkFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PlaylistWorks
   * const playlistWorks = await prisma.playlistWork.findMany()
   * 
   * // Get first 10 PlaylistWorks
   * const playlistWorks = await prisma.playlistWork.findMany({ take: 10 })
   * 
   * // Only select the `playlistId`
   * const playlistWorkWithPlaylistIdOnly = await prisma.playlistWork.findMany({ select: { playlistId: true } })
   * 
   */
  findMany<T extends PlaylistWorkFindManyArgs>(args?: Prisma.SelectSubset<T, PlaylistWorkFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PlaylistWorkPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PlaylistWork.
   * @param {PlaylistWorkCreateArgs} args - Arguments to create a PlaylistWork.
   * @example
   * // Create one PlaylistWork
   * const PlaylistWork = await prisma.playlistWork.create({
   *   data: {
   *     // ... data to create a PlaylistWork
   *   }
   * })
   * 
   */
  create<T extends PlaylistWorkCreateArgs>(args: Prisma.SelectSubset<T, PlaylistWorkCreateArgs<ExtArgs>>): Prisma.Prisma__PlaylistWorkClient<runtime.Types.Result.GetResult<Prisma.$PlaylistWorkPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PlaylistWorks.
   * @param {PlaylistWorkCreateManyArgs} args - Arguments to create many PlaylistWorks.
   * @example
   * // Create many PlaylistWorks
   * const playlistWork = await prisma.playlistWork.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PlaylistWorkCreateManyArgs>(args?: Prisma.SelectSubset<T, PlaylistWorkCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PlaylistWorks and returns the data saved in the database.
   * @param {PlaylistWorkCreateManyAndReturnArgs} args - Arguments to create many PlaylistWorks.
   * @example
   * // Create many PlaylistWorks
   * const playlistWork = await prisma.playlistWork.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PlaylistWorks and only return the `playlistId`
   * const playlistWorkWithPlaylistIdOnly = await prisma.playlistWork.createManyAndReturn({
   *   select: { playlistId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PlaylistWorkCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PlaylistWorkCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PlaylistWorkPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PlaylistWork.
   * @param {PlaylistWorkDeleteArgs} args - Arguments to delete one PlaylistWork.
   * @example
   * // Delete one PlaylistWork
   * const PlaylistWork = await prisma.playlistWork.delete({
   *   where: {
   *     // ... filter to delete one PlaylistWork
   *   }
   * })
   * 
   */
  delete<T extends PlaylistWorkDeleteArgs>(args: Prisma.SelectSubset<T, PlaylistWorkDeleteArgs<ExtArgs>>): Prisma.Prisma__PlaylistWorkClient<runtime.Types.Result.GetResult<Prisma.$PlaylistWorkPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PlaylistWork.
   * @param {PlaylistWorkUpdateArgs} args - Arguments to update one PlaylistWork.
   * @example
   * // Update one PlaylistWork
   * const playlistWork = await prisma.playlistWork.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PlaylistWorkUpdateArgs>(args: Prisma.SelectSubset<T, PlaylistWorkUpdateArgs<ExtArgs>>): Prisma.Prisma__PlaylistWorkClient<runtime.Types.Result.GetResult<Prisma.$PlaylistWorkPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PlaylistWorks.
   * @param {PlaylistWorkDeleteManyArgs} args - Arguments to filter PlaylistWorks to delete.
   * @example
   * // Delete a few PlaylistWorks
   * const { count } = await prisma.playlistWork.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PlaylistWorkDeleteManyArgs>(args?: Prisma.SelectSubset<T, PlaylistWorkDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PlaylistWorks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaylistWorkUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PlaylistWorks
   * const playlistWork = await prisma.playlistWork.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PlaylistWorkUpdateManyArgs>(args: Prisma.SelectSubset<T, PlaylistWorkUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PlaylistWorks and returns the data updated in the database.
   * @param {PlaylistWorkUpdateManyAndReturnArgs} args - Arguments to update many PlaylistWorks.
   * @example
   * // Update many PlaylistWorks
   * const playlistWork = await prisma.playlistWork.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PlaylistWorks and only return the `playlistId`
   * const playlistWorkWithPlaylistIdOnly = await prisma.playlistWork.updateManyAndReturn({
   *   select: { playlistId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PlaylistWorkUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PlaylistWorkUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PlaylistWorkPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PlaylistWork.
   * @param {PlaylistWorkUpsertArgs} args - Arguments to update or create a PlaylistWork.
   * @example
   * // Update or create a PlaylistWork
   * const playlistWork = await prisma.playlistWork.upsert({
   *   create: {
   *     // ... data to create a PlaylistWork
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PlaylistWork we want to update
   *   }
   * })
   */
  upsert<T extends PlaylistWorkUpsertArgs>(args: Prisma.SelectSubset<T, PlaylistWorkUpsertArgs<ExtArgs>>): Prisma.Prisma__PlaylistWorkClient<runtime.Types.Result.GetResult<Prisma.$PlaylistWorkPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PlaylistWorks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaylistWorkCountArgs} args - Arguments to filter PlaylistWorks to count.
   * @example
   * // Count the number of PlaylistWorks
   * const count = await prisma.playlistWork.count({
   *   where: {
   *     // ... the filter for the PlaylistWorks we want to count
   *   }
   * })
  **/
  count<T extends PlaylistWorkCountArgs>(
    args?: Prisma.Subset<T, PlaylistWorkCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PlaylistWorkCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PlaylistWork.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaylistWorkAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PlaylistWorkAggregateArgs>(args: Prisma.Subset<T, PlaylistWorkAggregateArgs>): Prisma.PrismaPromise<GetPlaylistWorkAggregateType<T>>

  /**
   * Group by PlaylistWork.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaylistWorkGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PlaylistWorkGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PlaylistWorkGroupByArgs['orderBy'] }
      : { orderBy?: PlaylistWorkGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PlaylistWorkGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPlaylistWorkGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PlaylistWork model
 */
readonly fields: PlaylistWorkFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PlaylistWork.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PlaylistWorkClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  playlist<T extends Prisma.PlaylistDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PlaylistDefaultArgs<ExtArgs>>): Prisma.Prisma__PlaylistClient<runtime.Types.Result.GetResult<Prisma.$PlaylistPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  work<T extends Prisma.WorkDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.WorkDefaultArgs<ExtArgs>>): Prisma.Prisma__WorkClient<runtime.Types.Result.GetResult<Prisma.$WorkPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PlaylistWork model
 */
export interface PlaylistWorkFieldRefs {
  readonly playlistId: Prisma.FieldRef<"PlaylistWork", 'String'>
  readonly workId: Prisma.FieldRef<"PlaylistWork", 'String'>
  readonly createdAt: Prisma.FieldRef<"PlaylistWork", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"PlaylistWork", 'DateTime'>
}
    

// Custom InputTypes
/**
 * PlaylistWork findUnique
 */
export type PlaylistWorkFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlaylistWork
   */
  select?: Prisma.PlaylistWorkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlaylistWork
   */
  omit?: Prisma.PlaylistWorkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaylistWorkInclude<ExtArgs> | null
  /**
   * Filter, which PlaylistWork to fetch.
   */
  where: Prisma.PlaylistWorkWhereUniqueInput
}

/**
 * PlaylistWork findUniqueOrThrow
 */
export type PlaylistWorkFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlaylistWork
   */
  select?: Prisma.PlaylistWorkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlaylistWork
   */
  omit?: Prisma.PlaylistWorkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaylistWorkInclude<ExtArgs> | null
  /**
   * Filter, which PlaylistWork to fetch.
   */
  where: Prisma.PlaylistWorkWhereUniqueInput
}

/**
 * PlaylistWork findFirst
 */
export type PlaylistWorkFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlaylistWork
   */
  select?: Prisma.PlaylistWorkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlaylistWork
   */
  omit?: Prisma.PlaylistWorkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaylistWorkInclude<ExtArgs> | null
  /**
   * Filter, which PlaylistWork to fetch.
   */
  where?: Prisma.PlaylistWorkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PlaylistWorks to fetch.
   */
  orderBy?: Prisma.PlaylistWorkOrderByWithRelationInput | Prisma.PlaylistWorkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PlaylistWorks.
   */
  cursor?: Prisma.PlaylistWorkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PlaylistWorks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PlaylistWorks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PlaylistWorks.
   */
  distinct?: Prisma.PlaylistWorkScalarFieldEnum | Prisma.PlaylistWorkScalarFieldEnum[]
}

/**
 * PlaylistWork findFirstOrThrow
 */
export type PlaylistWorkFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlaylistWork
   */
  select?: Prisma.PlaylistWorkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlaylistWork
   */
  omit?: Prisma.PlaylistWorkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaylistWorkInclude<ExtArgs> | null
  /**
   * Filter, which PlaylistWork to fetch.
   */
  where?: Prisma.PlaylistWorkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PlaylistWorks to fetch.
   */
  orderBy?: Prisma.PlaylistWorkOrderByWithRelationInput | Prisma.PlaylistWorkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PlaylistWorks.
   */
  cursor?: Prisma.PlaylistWorkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PlaylistWorks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PlaylistWorks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PlaylistWorks.
   */
  distinct?: Prisma.PlaylistWorkScalarFieldEnum | Prisma.PlaylistWorkScalarFieldEnum[]
}

/**
 * PlaylistWork findMany
 */
export type PlaylistWorkFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlaylistWork
   */
  select?: Prisma.PlaylistWorkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlaylistWork
   */
  omit?: Prisma.PlaylistWorkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaylistWorkInclude<ExtArgs> | null
  /**
   * Filter, which PlaylistWorks to fetch.
   */
  where?: Prisma.PlaylistWorkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PlaylistWorks to fetch.
   */
  orderBy?: Prisma.PlaylistWorkOrderByWithRelationInput | Prisma.PlaylistWorkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PlaylistWorks.
   */
  cursor?: Prisma.PlaylistWorkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PlaylistWorks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PlaylistWorks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PlaylistWorks.
   */
  distinct?: Prisma.PlaylistWorkScalarFieldEnum | Prisma.PlaylistWorkScalarFieldEnum[]
}

/**
 * PlaylistWork create
 */
export type PlaylistWorkCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlaylistWork
   */
  select?: Prisma.PlaylistWorkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlaylistWork
   */
  omit?: Prisma.PlaylistWorkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaylistWorkInclude<ExtArgs> | null
  /**
   * The data needed to create a PlaylistWork.
   */
  data: Prisma.XOR<Prisma.PlaylistWorkCreateInput, Prisma.PlaylistWorkUncheckedCreateInput>
}

/**
 * PlaylistWork createMany
 */
export type PlaylistWorkCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PlaylistWorks.
   */
  data: Prisma.PlaylistWorkCreateManyInput | Prisma.PlaylistWorkCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PlaylistWork createManyAndReturn
 */
export type PlaylistWorkCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlaylistWork
   */
  select?: Prisma.PlaylistWorkSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PlaylistWork
   */
  omit?: Prisma.PlaylistWorkOmit<ExtArgs> | null
  /**
   * The data used to create many PlaylistWorks.
   */
  data: Prisma.PlaylistWorkCreateManyInput | Prisma.PlaylistWorkCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaylistWorkIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * PlaylistWork update
 */
export type PlaylistWorkUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlaylistWork
   */
  select?: Prisma.PlaylistWorkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlaylistWork
   */
  omit?: Prisma.PlaylistWorkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaylistWorkInclude<ExtArgs> | null
  /**
   * The data needed to update a PlaylistWork.
   */
  data: Prisma.XOR<Prisma.PlaylistWorkUpdateInput, Prisma.PlaylistWorkUncheckedUpdateInput>
  /**
   * Choose, which PlaylistWork to update.
   */
  where: Prisma.PlaylistWorkWhereUniqueInput
}

/**
 * PlaylistWork updateMany
 */
export type PlaylistWorkUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PlaylistWorks.
   */
  data: Prisma.XOR<Prisma.PlaylistWorkUpdateManyMutationInput, Prisma.PlaylistWorkUncheckedUpdateManyInput>
  /**
   * Filter which PlaylistWorks to update
   */
  where?: Prisma.PlaylistWorkWhereInput
  /**
   * Limit how many PlaylistWorks to update.
   */
  limit?: number
}

/**
 * PlaylistWork updateManyAndReturn
 */
export type PlaylistWorkUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlaylistWork
   */
  select?: Prisma.PlaylistWorkSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PlaylistWork
   */
  omit?: Prisma.PlaylistWorkOmit<ExtArgs> | null
  /**
   * The data used to update PlaylistWorks.
   */
  data: Prisma.XOR<Prisma.PlaylistWorkUpdateManyMutationInput, Prisma.PlaylistWorkUncheckedUpdateManyInput>
  /**
   * Filter which PlaylistWorks to update
   */
  where?: Prisma.PlaylistWorkWhereInput
  /**
   * Limit how many PlaylistWorks to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaylistWorkIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * PlaylistWork upsert
 */
export type PlaylistWorkUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlaylistWork
   */
  select?: Prisma.PlaylistWorkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlaylistWork
   */
  omit?: Prisma.PlaylistWorkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaylistWorkInclude<ExtArgs> | null
  /**
   * The filter to search for the PlaylistWork to update in case it exists.
   */
  where: Prisma.PlaylistWorkWhereUniqueInput
  /**
   * In case the PlaylistWork found by the `where` argument doesn't exist, create a new PlaylistWork with this data.
   */
  create: Prisma.XOR<Prisma.PlaylistWorkCreateInput, Prisma.PlaylistWorkUncheckedCreateInput>
  /**
   * In case the PlaylistWork was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PlaylistWorkUpdateInput, Prisma.PlaylistWorkUncheckedUpdateInput>
}

/**
 * PlaylistWork delete
 */
export type PlaylistWorkDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlaylistWork
   */
  select?: Prisma.PlaylistWorkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlaylistWork
   */
  omit?: Prisma.PlaylistWorkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaylistWorkInclude<ExtArgs> | null
  /**
   * Filter which PlaylistWork to delete.
   */
  where: Prisma.PlaylistWorkWhereUniqueInput
}

/**
 * PlaylistWork deleteMany
 */
export type PlaylistWorkDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PlaylistWorks to delete
   */
  where?: Prisma.PlaylistWorkWhereInput
  /**
   * Limit how many PlaylistWorks to delete.
   */
  limit?: number
}

/**
 * PlaylistWork without action
 */
export type PlaylistWorkDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlaylistWork
   */
  select?: Prisma.PlaylistWorkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlaylistWork
   */
  omit?: Prisma.PlaylistWorkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaylistWorkInclude<ExtArgs> | null
}
