
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Playback` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Playback
 * 
 */
export type PlaybackModel = runtime.Types.Result.DefaultSelection<Prisma.$PlaybackPayload>

export type AggregatePlayback = {
  _count: PlaybackCountAggregateOutputType | null
  _avg: PlaybackAvgAggregateOutputType | null
  _sum: PlaybackSumAggregateOutputType | null
  _min: PlaybackMinAggregateOutputType | null
  _max: PlaybackMaxAggregateOutputType | null
}

export type PlaybackAvgAggregateOutputType = {
  position: number | null
  count: number | null
}

export type PlaybackSumAggregateOutputType = {
  position: number | null
  count: number | null
}

export type PlaybackMinAggregateOutputType = {
  workId: string | null
  position: number | null
  count: number | null
  lastAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PlaybackMaxAggregateOutputType = {
  workId: string | null
  position: number | null
  count: number | null
  lastAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PlaybackCountAggregateOutputType = {
  workId: number
  track: number
  tracks: number
  position: number
  count: number
  lastAt: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type PlaybackAvgAggregateInputType = {
  position?: true
  count?: true
}

export type PlaybackSumAggregateInputType = {
  position?: true
  count?: true
}

export type PlaybackMinAggregateInputType = {
  workId?: true
  position?: true
  count?: true
  lastAt?: true
  createdAt?: true
  updatedAt?: true
}

export type PlaybackMaxAggregateInputType = {
  workId?: true
  position?: true
  count?: true
  lastAt?: true
  createdAt?: true
  updatedAt?: true
}

export type PlaybackCountAggregateInputType = {
  workId?: true
  track?: true
  tracks?: true
  position?: true
  count?: true
  lastAt?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type PlaybackAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Playback to aggregate.
   */
  where?: Prisma.PlaybackWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Playbacks to fetch.
   */
  orderBy?: Prisma.PlaybackOrderByWithRelationInput | Prisma.PlaybackOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PlaybackWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Playbacks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Playbacks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Playbacks
  **/
  _count?: true | PlaybackCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PlaybackAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PlaybackSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PlaybackMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PlaybackMaxAggregateInputType
}

export type GetPlaybackAggregateType<T extends PlaybackAggregateArgs> = {
      [P in keyof T & keyof AggregatePlayback]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePlayback[P]>
    : Prisma.GetScalarType<T[P], AggregatePlayback[P]>
}




export type PlaybackGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PlaybackWhereInput
  orderBy?: Prisma.PlaybackOrderByWithAggregationInput | Prisma.PlaybackOrderByWithAggregationInput[]
  by: Prisma.PlaybackScalarFieldEnum[] | Prisma.PlaybackScalarFieldEnum
  having?: Prisma.PlaybackScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PlaybackCountAggregateInputType | true
  _avg?: PlaybackAvgAggregateInputType
  _sum?: PlaybackSumAggregateInputType
  _min?: PlaybackMinAggregateInputType
  _max?: PlaybackMaxAggregateInputType
}

export type PlaybackGroupByOutputType = {
  workId: string
  track: runtime.JsonValue
  tracks: runtime.JsonValue[]
  position: number
  count: number
  lastAt: Date
  createdAt: Date
  updatedAt: Date
  _count: PlaybackCountAggregateOutputType | null
  _avg: PlaybackAvgAggregateOutputType | null
  _sum: PlaybackSumAggregateOutputType | null
  _min: PlaybackMinAggregateOutputType | null
  _max: PlaybackMaxAggregateOutputType | null
}

type GetPlaybackGroupByPayload<T extends PlaybackGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PlaybackGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PlaybackGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PlaybackGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PlaybackGroupByOutputType[P]>
      }
    >
  >



export type PlaybackWhereInput = {
  AND?: Prisma.PlaybackWhereInput | Prisma.PlaybackWhereInput[]
  OR?: Prisma.PlaybackWhereInput[]
  NOT?: Prisma.PlaybackWhereInput | Prisma.PlaybackWhereInput[]
  workId?: Prisma.StringFilter<"Playback"> | string
  track?: Prisma.JsonFilter<"Playback">
  tracks?: Prisma.JsonNullableListFilter<"Playback">
  position?: Prisma.IntFilter<"Playback"> | number
  count?: Prisma.IntFilter<"Playback"> | number
  lastAt?: Prisma.DateTimeFilter<"Playback"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"Playback"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Playback"> | Date | string
  work?: Prisma.XOR<Prisma.WorkScalarRelationFilter, Prisma.WorkWhereInput>
}

export type PlaybackOrderByWithRelationInput = {
  workId?: Prisma.SortOrder
  track?: Prisma.SortOrder
  tracks?: Prisma.SortOrder
  position?: Prisma.SortOrder
  count?: Prisma.SortOrder
  lastAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  work?: Prisma.WorkOrderByWithRelationInput
}

export type PlaybackWhereUniqueInput = Prisma.AtLeast<{
  workId?: string
  AND?: Prisma.PlaybackWhereInput | Prisma.PlaybackWhereInput[]
  OR?: Prisma.PlaybackWhereInput[]
  NOT?: Prisma.PlaybackWhereInput | Prisma.PlaybackWhereInput[]
  track?: Prisma.JsonFilter<"Playback">
  tracks?: Prisma.JsonNullableListFilter<"Playback">
  position?: Prisma.IntFilter<"Playback"> | number
  count?: Prisma.IntFilter<"Playback"> | number
  lastAt?: Prisma.DateTimeFilter<"Playback"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"Playback"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Playback"> | Date | string
  work?: Prisma.XOR<Prisma.WorkScalarRelationFilter, Prisma.WorkWhereInput>
}, "workId">

export type PlaybackOrderByWithAggregationInput = {
  workId?: Prisma.SortOrder
  track?: Prisma.SortOrder
  tracks?: Prisma.SortOrder
  position?: Prisma.SortOrder
  count?: Prisma.SortOrder
  lastAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.PlaybackCountOrderByAggregateInput
  _avg?: Prisma.PlaybackAvgOrderByAggregateInput
  _max?: Prisma.PlaybackMaxOrderByAggregateInput
  _min?: Prisma.PlaybackMinOrderByAggregateInput
  _sum?: Prisma.PlaybackSumOrderByAggregateInput
}

export type PlaybackScalarWhereWithAggregatesInput = {
  AND?: Prisma.PlaybackScalarWhereWithAggregatesInput | Prisma.PlaybackScalarWhereWithAggregatesInput[]
  OR?: Prisma.PlaybackScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PlaybackScalarWhereWithAggregatesInput | Prisma.PlaybackScalarWhereWithAggregatesInput[]
  workId?: Prisma.StringWithAggregatesFilter<"Playback"> | string
  track?: Prisma.JsonWithAggregatesFilter<"Playback">
  tracks?: Prisma.JsonNullableListFilter<"Playback">
  position?: Prisma.IntWithAggregatesFilter<"Playback"> | number
  count?: Prisma.IntWithAggregatesFilter<"Playback"> | number
  lastAt?: Prisma.DateTimeWithAggregatesFilter<"Playback"> | Date | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Playback"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Playback"> | Date | string
}

export type PlaybackCreateInput = {
  track: Prisma.JsonNullValueInput | runtime.InputJsonValue
  tracks?: Prisma.PlaybackCreatetracksInput | runtime.InputJsonValue[]
  position?: number
  count?: number
  lastAt?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  work: Prisma.WorkCreateNestedOneWithoutPlaybackInput
}

export type PlaybackUncheckedCreateInput = {
  workId: string
  track: Prisma.JsonNullValueInput | runtime.InputJsonValue
  tracks?: Prisma.PlaybackCreatetracksInput | runtime.InputJsonValue[]
  position?: number
  count?: number
  lastAt?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PlaybackUpdateInput = {
  track?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  tracks?: Prisma.PlaybackUpdatetracksInput | runtime.InputJsonValue[]
  position?: Prisma.IntFieldUpdateOperationsInput | number
  count?: Prisma.IntFieldUpdateOperationsInput | number
  lastAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  work?: Prisma.WorkUpdateOneRequiredWithoutPlaybackNestedInput
}

export type PlaybackUncheckedUpdateInput = {
  workId?: Prisma.StringFieldUpdateOperationsInput | string
  track?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  tracks?: Prisma.PlaybackUpdatetracksInput | runtime.InputJsonValue[]
  position?: Prisma.IntFieldUpdateOperationsInput | number
  count?: Prisma.IntFieldUpdateOperationsInput | number
  lastAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PlaybackCreateManyInput = {
  workId: string
  track: Prisma.JsonNullValueInput | runtime.InputJsonValue
  tracks?: Prisma.PlaybackCreatetracksInput | runtime.InputJsonValue[]
  position?: number
  count?: number
  lastAt?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PlaybackUpdateManyMutationInput = {
  track?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  tracks?: Prisma.PlaybackUpdatetracksInput | runtime.InputJsonValue[]
  position?: Prisma.IntFieldUpdateOperationsInput | number
  count?: Prisma.IntFieldUpdateOperationsInput | number
  lastAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PlaybackUncheckedUpdateManyInput = {
  workId?: Prisma.StringFieldUpdateOperationsInput | string
  track?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  tracks?: Prisma.PlaybackUpdatetracksInput | runtime.InputJsonValue[]
  position?: Prisma.IntFieldUpdateOperationsInput | number
  count?: Prisma.IntFieldUpdateOperationsInput | number
  lastAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PlaybackNullableScalarRelationFilter = {
  is?: Prisma.PlaybackWhereInput | null
  isNot?: Prisma.PlaybackWhereInput | null
}

export type PlaybackCountOrderByAggregateInput = {
  workId?: Prisma.SortOrder
  track?: Prisma.SortOrder
  tracks?: Prisma.SortOrder
  position?: Prisma.SortOrder
  count?: Prisma.SortOrder
  lastAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PlaybackAvgOrderByAggregateInput = {
  position?: Prisma.SortOrder
  count?: Prisma.SortOrder
}

export type PlaybackMaxOrderByAggregateInput = {
  workId?: Prisma.SortOrder
  position?: Prisma.SortOrder
  count?: Prisma.SortOrder
  lastAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PlaybackMinOrderByAggregateInput = {
  workId?: Prisma.SortOrder
  position?: Prisma.SortOrder
  count?: Prisma.SortOrder
  lastAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PlaybackSumOrderByAggregateInput = {
  position?: Prisma.SortOrder
  count?: Prisma.SortOrder
}

export type PlaybackCreateNestedOneWithoutWorkInput = {
  create?: Prisma.XOR<Prisma.PlaybackCreateWithoutWorkInput, Prisma.PlaybackUncheckedCreateWithoutWorkInput>
  connectOrCreate?: Prisma.PlaybackCreateOrConnectWithoutWorkInput
  connect?: Prisma.PlaybackWhereUniqueInput
}

export type PlaybackUncheckedCreateNestedOneWithoutWorkInput = {
  create?: Prisma.XOR<Prisma.PlaybackCreateWithoutWorkInput, Prisma.PlaybackUncheckedCreateWithoutWorkInput>
  connectOrCreate?: Prisma.PlaybackCreateOrConnectWithoutWorkInput
  connect?: Prisma.PlaybackWhereUniqueInput
}

export type PlaybackUpdateOneWithoutWorkNestedInput = {
  create?: Prisma.XOR<Prisma.PlaybackCreateWithoutWorkInput, Prisma.PlaybackUncheckedCreateWithoutWorkInput>
  connectOrCreate?: Prisma.PlaybackCreateOrConnectWithoutWorkInput
  upsert?: Prisma.PlaybackUpsertWithoutWorkInput
  disconnect?: Prisma.PlaybackWhereInput | boolean
  delete?: Prisma.PlaybackWhereInput | boolean
  connect?: Prisma.PlaybackWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PlaybackUpdateToOneWithWhereWithoutWorkInput, Prisma.PlaybackUpdateWithoutWorkInput>, Prisma.PlaybackUncheckedUpdateWithoutWorkInput>
}

export type PlaybackUncheckedUpdateOneWithoutWorkNestedInput = {
  create?: Prisma.XOR<Prisma.PlaybackCreateWithoutWorkInput, Prisma.PlaybackUncheckedCreateWithoutWorkInput>
  connectOrCreate?: Prisma.PlaybackCreateOrConnectWithoutWorkInput
  upsert?: Prisma.PlaybackUpsertWithoutWorkInput
  disconnect?: Prisma.PlaybackWhereInput | boolean
  delete?: Prisma.PlaybackWhereInput | boolean
  connect?: Prisma.PlaybackWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PlaybackUpdateToOneWithWhereWithoutWorkInput, Prisma.PlaybackUpdateWithoutWorkInput>, Prisma.PlaybackUncheckedUpdateWithoutWorkInput>
}

export type PlaybackCreatetracksInput = {
  set: runtime.InputJsonValue[]
}

export type PlaybackUpdatetracksInput = {
  set?: runtime.InputJsonValue[]
  push?: runtime.InputJsonValue | runtime.InputJsonValue[]
}

export type PlaybackCreateWithoutWorkInput = {
  track: Prisma.JsonNullValueInput | runtime.InputJsonValue
  tracks?: Prisma.PlaybackCreatetracksInput | runtime.InputJsonValue[]
  position?: number
  count?: number
  lastAt?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PlaybackUncheckedCreateWithoutWorkInput = {
  track: Prisma.JsonNullValueInput | runtime.InputJsonValue
  tracks?: Prisma.PlaybackCreatetracksInput | runtime.InputJsonValue[]
  position?: number
  count?: number
  lastAt?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PlaybackCreateOrConnectWithoutWorkInput = {
  where: Prisma.PlaybackWhereUniqueInput
  create: Prisma.XOR<Prisma.PlaybackCreateWithoutWorkInput, Prisma.PlaybackUncheckedCreateWithoutWorkInput>
}

export type PlaybackUpsertWithoutWorkInput = {
  update: Prisma.XOR<Prisma.PlaybackUpdateWithoutWorkInput, Prisma.PlaybackUncheckedUpdateWithoutWorkInput>
  create: Prisma.XOR<Prisma.PlaybackCreateWithoutWorkInput, Prisma.PlaybackUncheckedCreateWithoutWorkInput>
  where?: Prisma.PlaybackWhereInput
}

export type PlaybackUpdateToOneWithWhereWithoutWorkInput = {
  where?: Prisma.PlaybackWhereInput
  data: Prisma.XOR<Prisma.PlaybackUpdateWithoutWorkInput, Prisma.PlaybackUncheckedUpdateWithoutWorkInput>
}

export type PlaybackUpdateWithoutWorkInput = {
  track?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  tracks?: Prisma.PlaybackUpdatetracksInput | runtime.InputJsonValue[]
  position?: Prisma.IntFieldUpdateOperationsInput | number
  count?: Prisma.IntFieldUpdateOperationsInput | number
  lastAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PlaybackUncheckedUpdateWithoutWorkInput = {
  track?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  tracks?: Prisma.PlaybackUpdatetracksInput | runtime.InputJsonValue[]
  position?: Prisma.IntFieldUpdateOperationsInput | number
  count?: Prisma.IntFieldUpdateOperationsInput | number
  lastAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type PlaybackSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  workId?: boolean
  track?: boolean
  tracks?: boolean
  position?: boolean
  count?: boolean
  lastAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  work?: boolean | Prisma.WorkDefaultArgs<ExtArgs>
}, ExtArgs["result"]["playback"]>

export type PlaybackSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  workId?: boolean
  track?: boolean
  tracks?: boolean
  position?: boolean
  count?: boolean
  lastAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  work?: boolean | Prisma.WorkDefaultArgs<ExtArgs>
}, ExtArgs["result"]["playback"]>

export type PlaybackSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  workId?: boolean
  track?: boolean
  tracks?: boolean
  position?: boolean
  count?: boolean
  lastAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  work?: boolean | Prisma.WorkDefaultArgs<ExtArgs>
}, ExtArgs["result"]["playback"]>

export type PlaybackSelectScalar = {
  workId?: boolean
  track?: boolean
  tracks?: boolean
  position?: boolean
  count?: boolean
  lastAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type PlaybackOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"workId" | "track" | "tracks" | "position" | "count" | "lastAt" | "createdAt" | "updatedAt", ExtArgs["result"]["playback"]>
export type PlaybackInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  work?: boolean | Prisma.WorkDefaultArgs<ExtArgs>
}
export type PlaybackIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  work?: boolean | Prisma.WorkDefaultArgs<ExtArgs>
}
export type PlaybackIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  work?: boolean | Prisma.WorkDefaultArgs<ExtArgs>
}

export type $PlaybackPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Playback"
  objects: {
    work: Prisma.$WorkPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    workId: string
    track: runtime.JsonValue
    tracks: runtime.JsonValue[]
    position: number
    count: number
    lastAt: Date
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["playback"]>
  composites: {}
}

export type PlaybackGetPayload<S extends boolean | null | undefined | PlaybackDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PlaybackPayload, S>

export type PlaybackCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PlaybackFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PlaybackCountAggregateInputType | true
  }

export interface PlaybackDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Playback'], meta: { name: 'Playback' } }
  /**
   * Find zero or one Playback that matches the filter.
   * @param {PlaybackFindUniqueArgs} args - Arguments to find a Playback
   * @example
   * // Get one Playback
   * const playback = await prisma.playback.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PlaybackFindUniqueArgs>(args: Prisma.SelectSubset<T, PlaybackFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PlaybackClient<runtime.Types.Result.GetResult<Prisma.$PlaybackPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Playback that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PlaybackFindUniqueOrThrowArgs} args - Arguments to find a Playback
   * @example
   * // Get one Playback
   * const playback = await prisma.playback.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PlaybackFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PlaybackFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PlaybackClient<runtime.Types.Result.GetResult<Prisma.$PlaybackPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Playback that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaybackFindFirstArgs} args - Arguments to find a Playback
   * @example
   * // Get one Playback
   * const playback = await prisma.playback.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PlaybackFindFirstArgs>(args?: Prisma.SelectSubset<T, PlaybackFindFirstArgs<ExtArgs>>): Prisma.Prisma__PlaybackClient<runtime.Types.Result.GetResult<Prisma.$PlaybackPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Playback that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaybackFindFirstOrThrowArgs} args - Arguments to find a Playback
   * @example
   * // Get one Playback
   * const playback = await prisma.playback.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PlaybackFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PlaybackFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PlaybackClient<runtime.Types.Result.GetResult<Prisma.$PlaybackPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Playbacks that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaybackFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Playbacks
   * const playbacks = await prisma.playback.findMany()
   * 
   * // Get first 10 Playbacks
   * const playbacks = await prisma.playback.findMany({ take: 10 })
   * 
   * // Only select the `workId`
   * const playbackWithWorkIdOnly = await prisma.playback.findMany({ select: { workId: true } })
   * 
   */
  findMany<T extends PlaybackFindManyArgs>(args?: Prisma.SelectSubset<T, PlaybackFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PlaybackPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Playback.
   * @param {PlaybackCreateArgs} args - Arguments to create a Playback.
   * @example
   * // Create one Playback
   * const Playback = await prisma.playback.create({
   *   data: {
   *     // ... data to create a Playback
   *   }
   * })
   * 
   */
  create<T extends PlaybackCreateArgs>(args: Prisma.SelectSubset<T, PlaybackCreateArgs<ExtArgs>>): Prisma.Prisma__PlaybackClient<runtime.Types.Result.GetResult<Prisma.$PlaybackPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Playbacks.
   * @param {PlaybackCreateManyArgs} args - Arguments to create many Playbacks.
   * @example
   * // Create many Playbacks
   * const playback = await prisma.playback.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PlaybackCreateManyArgs>(args?: Prisma.SelectSubset<T, PlaybackCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Playbacks and returns the data saved in the database.
   * @param {PlaybackCreateManyAndReturnArgs} args - Arguments to create many Playbacks.
   * @example
   * // Create many Playbacks
   * const playback = await prisma.playback.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Playbacks and only return the `workId`
   * const playbackWithWorkIdOnly = await prisma.playback.createManyAndReturn({
   *   select: { workId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PlaybackCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PlaybackCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PlaybackPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Playback.
   * @param {PlaybackDeleteArgs} args - Arguments to delete one Playback.
   * @example
   * // Delete one Playback
   * const Playback = await prisma.playback.delete({
   *   where: {
   *     // ... filter to delete one Playback
   *   }
   * })
   * 
   */
  delete<T extends PlaybackDeleteArgs>(args: Prisma.SelectSubset<T, PlaybackDeleteArgs<ExtArgs>>): Prisma.Prisma__PlaybackClient<runtime.Types.Result.GetResult<Prisma.$PlaybackPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Playback.
   * @param {PlaybackUpdateArgs} args - Arguments to update one Playback.
   * @example
   * // Update one Playback
   * const playback = await prisma.playback.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PlaybackUpdateArgs>(args: Prisma.SelectSubset<T, PlaybackUpdateArgs<ExtArgs>>): Prisma.Prisma__PlaybackClient<runtime.Types.Result.GetResult<Prisma.$PlaybackPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Playbacks.
   * @param {PlaybackDeleteManyArgs} args - Arguments to filter Playbacks to delete.
   * @example
   * // Delete a few Playbacks
   * const { count } = await prisma.playback.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PlaybackDeleteManyArgs>(args?: Prisma.SelectSubset<T, PlaybackDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Playbacks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaybackUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Playbacks
   * const playback = await prisma.playback.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PlaybackUpdateManyArgs>(args: Prisma.SelectSubset<T, PlaybackUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Playbacks and returns the data updated in the database.
   * @param {PlaybackUpdateManyAndReturnArgs} args - Arguments to update many Playbacks.
   * @example
   * // Update many Playbacks
   * const playback = await prisma.playback.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Playbacks and only return the `workId`
   * const playbackWithWorkIdOnly = await prisma.playback.updateManyAndReturn({
   *   select: { workId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PlaybackUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PlaybackUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PlaybackPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Playback.
   * @param {PlaybackUpsertArgs} args - Arguments to update or create a Playback.
   * @example
   * // Update or create a Playback
   * const playback = await prisma.playback.upsert({
   *   create: {
   *     // ... data to create a Playback
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Playback we want to update
   *   }
   * })
   */
  upsert<T extends PlaybackUpsertArgs>(args: Prisma.SelectSubset<T, PlaybackUpsertArgs<ExtArgs>>): Prisma.Prisma__PlaybackClient<runtime.Types.Result.GetResult<Prisma.$PlaybackPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Playbacks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaybackCountArgs} args - Arguments to filter Playbacks to count.
   * @example
   * // Count the number of Playbacks
   * const count = await prisma.playback.count({
   *   where: {
   *     // ... the filter for the Playbacks we want to count
   *   }
   * })
  **/
  count<T extends PlaybackCountArgs>(
    args?: Prisma.Subset<T, PlaybackCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PlaybackCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Playback.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaybackAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PlaybackAggregateArgs>(args: Prisma.Subset<T, PlaybackAggregateArgs>): Prisma.PrismaPromise<GetPlaybackAggregateType<T>>

  /**
   * Group by Playback.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaybackGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PlaybackGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PlaybackGroupByArgs['orderBy'] }
      : { orderBy?: PlaybackGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PlaybackGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPlaybackGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Playback model
 */
readonly fields: PlaybackFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Playback.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PlaybackClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  work<T extends Prisma.WorkDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.WorkDefaultArgs<ExtArgs>>): Prisma.Prisma__WorkClient<runtime.Types.Result.GetResult<Prisma.$WorkPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Playback model
 */
export interface PlaybackFieldRefs {
  readonly workId: Prisma.FieldRef<"Playback", 'String'>
  readonly track: Prisma.FieldRef<"Playback", 'Json'>
  readonly tracks: Prisma.FieldRef<"Playback", 'Json[]'>
  readonly position: Prisma.FieldRef<"Playback", 'Int'>
  readonly count: Prisma.FieldRef<"Playback", 'Int'>
  readonly lastAt: Prisma.FieldRef<"Playback", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"Playback", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Playback", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Playback findUnique
 */
export type PlaybackFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Playback
   */
  select?: Prisma.PlaybackSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Playback
   */
  omit?: Prisma.PlaybackOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaybackInclude<ExtArgs> | null
  /**
   * Filter, which Playback to fetch.
   */
  where: Prisma.PlaybackWhereUniqueInput
}

/**
 * Playback findUniqueOrThrow
 */
export type PlaybackFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Playback
   */
  select?: Prisma.PlaybackSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Playback
   */
  omit?: Prisma.PlaybackOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaybackInclude<ExtArgs> | null
  /**
   * Filter, which Playback to fetch.
   */
  where: Prisma.PlaybackWhereUniqueInput
}

/**
 * Playback findFirst
 */
export type PlaybackFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Playback
   */
  select?: Prisma.PlaybackSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Playback
   */
  omit?: Prisma.PlaybackOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaybackInclude<ExtArgs> | null
  /**
   * Filter, which Playback to fetch.
   */
  where?: Prisma.PlaybackWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Playbacks to fetch.
   */
  orderBy?: Prisma.PlaybackOrderByWithRelationInput | Prisma.PlaybackOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Playbacks.
   */
  cursor?: Prisma.PlaybackWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Playbacks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Playbacks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Playbacks.
   */
  distinct?: Prisma.PlaybackScalarFieldEnum | Prisma.PlaybackScalarFieldEnum[]
}

/**
 * Playback findFirstOrThrow
 */
export type PlaybackFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Playback
   */
  select?: Prisma.PlaybackSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Playback
   */
  omit?: Prisma.PlaybackOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaybackInclude<ExtArgs> | null
  /**
   * Filter, which Playback to fetch.
   */
  where?: Prisma.PlaybackWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Playbacks to fetch.
   */
  orderBy?: Prisma.PlaybackOrderByWithRelationInput | Prisma.PlaybackOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Playbacks.
   */
  cursor?: Prisma.PlaybackWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Playbacks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Playbacks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Playbacks.
   */
  distinct?: Prisma.PlaybackScalarFieldEnum | Prisma.PlaybackScalarFieldEnum[]
}

/**
 * Playback findMany
 */
export type PlaybackFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Playback
   */
  select?: Prisma.PlaybackSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Playback
   */
  omit?: Prisma.PlaybackOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaybackInclude<ExtArgs> | null
  /**
   * Filter, which Playbacks to fetch.
   */
  where?: Prisma.PlaybackWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Playbacks to fetch.
   */
  orderBy?: Prisma.PlaybackOrderByWithRelationInput | Prisma.PlaybackOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Playbacks.
   */
  cursor?: Prisma.PlaybackWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Playbacks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Playbacks.
   */
  skip?: number
  distinct?: Prisma.PlaybackScalarFieldEnum | Prisma.PlaybackScalarFieldEnum[]
}

/**
 * Playback create
 */
export type PlaybackCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Playback
   */
  select?: Prisma.PlaybackSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Playback
   */
  omit?: Prisma.PlaybackOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaybackInclude<ExtArgs> | null
  /**
   * The data needed to create a Playback.
   */
  data: Prisma.XOR<Prisma.PlaybackCreateInput, Prisma.PlaybackUncheckedCreateInput>
}

/**
 * Playback createMany
 */
export type PlaybackCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Playbacks.
   */
  data: Prisma.PlaybackCreateManyInput | Prisma.PlaybackCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Playback createManyAndReturn
 */
export type PlaybackCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Playback
   */
  select?: Prisma.PlaybackSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Playback
   */
  omit?: Prisma.PlaybackOmit<ExtArgs> | null
  /**
   * The data used to create many Playbacks.
   */
  data: Prisma.PlaybackCreateManyInput | Prisma.PlaybackCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaybackIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Playback update
 */
export type PlaybackUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Playback
   */
  select?: Prisma.PlaybackSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Playback
   */
  omit?: Prisma.PlaybackOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaybackInclude<ExtArgs> | null
  /**
   * The data needed to update a Playback.
   */
  data: Prisma.XOR<Prisma.PlaybackUpdateInput, Prisma.PlaybackUncheckedUpdateInput>
  /**
   * Choose, which Playback to update.
   */
  where: Prisma.PlaybackWhereUniqueInput
}

/**
 * Playback updateMany
 */
export type PlaybackUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Playbacks.
   */
  data: Prisma.XOR<Prisma.PlaybackUpdateManyMutationInput, Prisma.PlaybackUncheckedUpdateManyInput>
  /**
   * Filter which Playbacks to update
   */
  where?: Prisma.PlaybackWhereInput
  /**
   * Limit how many Playbacks to update.
   */
  limit?: number
}

/**
 * Playback updateManyAndReturn
 */
export type PlaybackUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Playback
   */
  select?: Prisma.PlaybackSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Playback
   */
  omit?: Prisma.PlaybackOmit<ExtArgs> | null
  /**
   * The data used to update Playbacks.
   */
  data: Prisma.XOR<Prisma.PlaybackUpdateManyMutationInput, Prisma.PlaybackUncheckedUpdateManyInput>
  /**
   * Filter which Playbacks to update
   */
  where?: Prisma.PlaybackWhereInput
  /**
   * Limit how many Playbacks to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaybackIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Playback upsert
 */
export type PlaybackUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Playback
   */
  select?: Prisma.PlaybackSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Playback
   */
  omit?: Prisma.PlaybackOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaybackInclude<ExtArgs> | null
  /**
   * The filter to search for the Playback to update in case it exists.
   */
  where: Prisma.PlaybackWhereUniqueInput
  /**
   * In case the Playback found by the `where` argument doesn't exist, create a new Playback with this data.
   */
  create: Prisma.XOR<Prisma.PlaybackCreateInput, Prisma.PlaybackUncheckedCreateInput>
  /**
   * In case the Playback was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PlaybackUpdateInput, Prisma.PlaybackUncheckedUpdateInput>
}

/**
 * Playback delete
 */
export type PlaybackDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Playback
   */
  select?: Prisma.PlaybackSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Playback
   */
  omit?: Prisma.PlaybackOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaybackInclude<ExtArgs> | null
  /**
   * Filter which Playback to delete.
   */
  where: Prisma.PlaybackWhereUniqueInput
}

/**
 * Playback deleteMany
 */
export type PlaybackDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Playbacks to delete
   */
  where?: Prisma.PlaybackWhereInput
  /**
   * Limit how many Playbacks to delete.
   */
  limit?: number
}

/**
 * Playback without action
 */
export type PlaybackDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Playback
   */
  select?: Prisma.PlaybackSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Playback
   */
  omit?: Prisma.PlaybackOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaybackInclude<ExtArgs> | null
}
