
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TranslationInfo` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model TranslationInfo
 * 
 */
export type TranslationInfoModel = runtime.Types.Result.DefaultSelection<Prisma.$TranslationInfoPayload>

export type AggregateTranslationInfo = {
  _count: TranslationInfoCountAggregateOutputType | null
  _min: TranslationInfoMinAggregateOutputType | null
  _max: TranslationInfoMaxAggregateOutputType | null
}

export type TranslationInfoMinAggregateOutputType = {
  workId: string | null
  isVolunteer: boolean | null
  isOriginal: boolean | null
  isParent: boolean | null
  isChild: boolean | null
  isTranslationBonusChild: boolean | null
  originalWorkno: string | null
  parentWorkno: string | null
  lang: string | null
}

export type TranslationInfoMaxAggregateOutputType = {
  workId: string | null
  isVolunteer: boolean | null
  isOriginal: boolean | null
  isParent: boolean | null
  isChild: boolean | null
  isTranslationBonusChild: boolean | null
  originalWorkno: string | null
  parentWorkno: string | null
  lang: string | null
}

export type TranslationInfoCountAggregateOutputType = {
  workId: number
  isVolunteer: number
  isOriginal: number
  isParent: number
  isChild: number
  isTranslationBonusChild: number
  originalWorkno: number
  parentWorkno: number
  childWorknos: number
  lang: number
  _all: number
}


export type TranslationInfoMinAggregateInputType = {
  workId?: true
  isVolunteer?: true
  isOriginal?: true
  isParent?: true
  isChild?: true
  isTranslationBonusChild?: true
  originalWorkno?: true
  parentWorkno?: true
  lang?: true
}

export type TranslationInfoMaxAggregateInputType = {
  workId?: true
  isVolunteer?: true
  isOriginal?: true
  isParent?: true
  isChild?: true
  isTranslationBonusChild?: true
  originalWorkno?: true
  parentWorkno?: true
  lang?: true
}

export type TranslationInfoCountAggregateInputType = {
  workId?: true
  isVolunteer?: true
  isOriginal?: true
  isParent?: true
  isChild?: true
  isTranslationBonusChild?: true
  originalWorkno?: true
  parentWorkno?: true
  childWorknos?: true
  lang?: true
  _all?: true
}

export type TranslationInfoAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TranslationInfo to aggregate.
   */
  where?: Prisma.TranslationInfoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TranslationInfos to fetch.
   */
  orderBy?: Prisma.TranslationInfoOrderByWithRelationInput | Prisma.TranslationInfoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TranslationInfoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TranslationInfos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TranslationInfos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TranslationInfos
  **/
  _count?: true | TranslationInfoCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TranslationInfoMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TranslationInfoMaxAggregateInputType
}

export type GetTranslationInfoAggregateType<T extends TranslationInfoAggregateArgs> = {
      [P in keyof T & keyof AggregateTranslationInfo]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTranslationInfo[P]>
    : Prisma.GetScalarType<T[P], AggregateTranslationInfo[P]>
}




export type TranslationInfoGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TranslationInfoWhereInput
  orderBy?: Prisma.TranslationInfoOrderByWithAggregationInput | Prisma.TranslationInfoOrderByWithAggregationInput[]
  by: Prisma.TranslationInfoScalarFieldEnum[] | Prisma.TranslationInfoScalarFieldEnum
  having?: Prisma.TranslationInfoScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TranslationInfoCountAggregateInputType | true
  _min?: TranslationInfoMinAggregateInputType
  _max?: TranslationInfoMaxAggregateInputType
}

export type TranslationInfoGroupByOutputType = {
  workId: string
  isVolunteer: boolean
  isOriginal: boolean
  isParent: boolean
  isChild: boolean
  isTranslationBonusChild: boolean
  originalWorkno: string | null
  parentWorkno: string | null
  childWorknos: string[]
  lang: string | null
  _count: TranslationInfoCountAggregateOutputType | null
  _min: TranslationInfoMinAggregateOutputType | null
  _max: TranslationInfoMaxAggregateOutputType | null
}

type GetTranslationInfoGroupByPayload<T extends TranslationInfoGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TranslationInfoGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TranslationInfoGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TranslationInfoGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TranslationInfoGroupByOutputType[P]>
      }
    >
  >



export type TranslationInfoWhereInput = {
  AND?: Prisma.TranslationInfoWhereInput | Prisma.TranslationInfoWhereInput[]
  OR?: Prisma.TranslationInfoWhereInput[]
  NOT?: Prisma.TranslationInfoWhereInput | Prisma.TranslationInfoWhereInput[]
  workId?: Prisma.StringFilter<"TranslationInfo"> | string
  isVolunteer?: Prisma.BoolFilter<"TranslationInfo"> | boolean
  isOriginal?: Prisma.BoolFilter<"TranslationInfo"> | boolean
  isParent?: Prisma.BoolFilter<"TranslationInfo"> | boolean
  isChild?: Prisma.BoolFilter<"TranslationInfo"> | boolean
  isTranslationBonusChild?: Prisma.BoolFilter<"TranslationInfo"> | boolean
  originalWorkno?: Prisma.StringNullableFilter<"TranslationInfo"> | string | null
  parentWorkno?: Prisma.StringNullableFilter<"TranslationInfo"> | string | null
  childWorknos?: Prisma.StringNullableListFilter<"TranslationInfo">
  lang?: Prisma.StringNullableFilter<"TranslationInfo"> | string | null
  work?: Prisma.XOR<Prisma.WorkScalarRelationFilter, Prisma.WorkWhereInput>
}

export type TranslationInfoOrderByWithRelationInput = {
  workId?: Prisma.SortOrder
  isVolunteer?: Prisma.SortOrder
  isOriginal?: Prisma.SortOrder
  isParent?: Prisma.SortOrder
  isChild?: Prisma.SortOrder
  isTranslationBonusChild?: Prisma.SortOrder
  originalWorkno?: Prisma.SortOrderInput | Prisma.SortOrder
  parentWorkno?: Prisma.SortOrderInput | Prisma.SortOrder
  childWorknos?: Prisma.SortOrder
  lang?: Prisma.SortOrderInput | Prisma.SortOrder
  work?: Prisma.WorkOrderByWithRelationInput
}

export type TranslationInfoWhereUniqueInput = Prisma.AtLeast<{
  workId?: string
  AND?: Prisma.TranslationInfoWhereInput | Prisma.TranslationInfoWhereInput[]
  OR?: Prisma.TranslationInfoWhereInput[]
  NOT?: Prisma.TranslationInfoWhereInput | Prisma.TranslationInfoWhereInput[]
  isVolunteer?: Prisma.BoolFilter<"TranslationInfo"> | boolean
  isOriginal?: Prisma.BoolFilter<"TranslationInfo"> | boolean
  isParent?: Prisma.BoolFilter<"TranslationInfo"> | boolean
  isChild?: Prisma.BoolFilter<"TranslationInfo"> | boolean
  isTranslationBonusChild?: Prisma.BoolFilter<"TranslationInfo"> | boolean
  originalWorkno?: Prisma.StringNullableFilter<"TranslationInfo"> | string | null
  parentWorkno?: Prisma.StringNullableFilter<"TranslationInfo"> | string | null
  childWorknos?: Prisma.StringNullableListFilter<"TranslationInfo">
  lang?: Prisma.StringNullableFilter<"TranslationInfo"> | string | null
  work?: Prisma.XOR<Prisma.WorkScalarRelationFilter, Prisma.WorkWhereInput>
}, "workId">

export type TranslationInfoOrderByWithAggregationInput = {
  workId?: Prisma.SortOrder
  isVolunteer?: Prisma.SortOrder
  isOriginal?: Prisma.SortOrder
  isParent?: Prisma.SortOrder
  isChild?: Prisma.SortOrder
  isTranslationBonusChild?: Prisma.SortOrder
  originalWorkno?: Prisma.SortOrderInput | Prisma.SortOrder
  parentWorkno?: Prisma.SortOrderInput | Prisma.SortOrder
  childWorknos?: Prisma.SortOrder
  lang?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.TranslationInfoCountOrderByAggregateInput
  _max?: Prisma.TranslationInfoMaxOrderByAggregateInput
  _min?: Prisma.TranslationInfoMinOrderByAggregateInput
}

export type TranslationInfoScalarWhereWithAggregatesInput = {
  AND?: Prisma.TranslationInfoScalarWhereWithAggregatesInput | Prisma.TranslationInfoScalarWhereWithAggregatesInput[]
  OR?: Prisma.TranslationInfoScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TranslationInfoScalarWhereWithAggregatesInput | Prisma.TranslationInfoScalarWhereWithAggregatesInput[]
  workId?: Prisma.StringWithAggregatesFilter<"TranslationInfo"> | string
  isVolunteer?: Prisma.BoolWithAggregatesFilter<"TranslationInfo"> | boolean
  isOriginal?: Prisma.BoolWithAggregatesFilter<"TranslationInfo"> | boolean
  isParent?: Prisma.BoolWithAggregatesFilter<"TranslationInfo"> | boolean
  isChild?: Prisma.BoolWithAggregatesFilter<"TranslationInfo"> | boolean
  isTranslationBonusChild?: Prisma.BoolWithAggregatesFilter<"TranslationInfo"> | boolean
  originalWorkno?: Prisma.StringNullableWithAggregatesFilter<"TranslationInfo"> | string | null
  parentWorkno?: Prisma.StringNullableWithAggregatesFilter<"TranslationInfo"> | string | null
  childWorknos?: Prisma.StringNullableListFilter<"TranslationInfo">
  lang?: Prisma.StringNullableWithAggregatesFilter<"TranslationInfo"> | string | null
}

export type TranslationInfoCreateInput = {
  isVolunteer: boolean
  isOriginal: boolean
  isParent: boolean
  isChild: boolean
  isTranslationBonusChild: boolean
  originalWorkno?: string | null
  parentWorkno?: string | null
  childWorknos?: Prisma.TranslationInfoCreatechildWorknosInput | string[]
  lang?: string | null
  work: Prisma.WorkCreateNestedOneWithoutTranslationInfoInput
}

export type TranslationInfoUncheckedCreateInput = {
  workId: string
  isVolunteer: boolean
  isOriginal: boolean
  isParent: boolean
  isChild: boolean
  isTranslationBonusChild: boolean
  originalWorkno?: string | null
  parentWorkno?: string | null
  childWorknos?: Prisma.TranslationInfoCreatechildWorknosInput | string[]
  lang?: string | null
}

export type TranslationInfoUpdateInput = {
  isVolunteer?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isOriginal?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isParent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isChild?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isTranslationBonusChild?: Prisma.BoolFieldUpdateOperationsInput | boolean
  originalWorkno?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  parentWorkno?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  childWorknos?: Prisma.TranslationInfoUpdatechildWorknosInput | string[]
  lang?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  work?: Prisma.WorkUpdateOneRequiredWithoutTranslationInfoNestedInput
}

export type TranslationInfoUncheckedUpdateInput = {
  workId?: Prisma.StringFieldUpdateOperationsInput | string
  isVolunteer?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isOriginal?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isParent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isChild?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isTranslationBonusChild?: Prisma.BoolFieldUpdateOperationsInput | boolean
  originalWorkno?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  parentWorkno?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  childWorknos?: Prisma.TranslationInfoUpdatechildWorknosInput | string[]
  lang?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type TranslationInfoCreateManyInput = {
  workId: string
  isVolunteer: boolean
  isOriginal: boolean
  isParent: boolean
  isChild: boolean
  isTranslationBonusChild: boolean
  originalWorkno?: string | null
  parentWorkno?: string | null
  childWorknos?: Prisma.TranslationInfoCreatechildWorknosInput | string[]
  lang?: string | null
}

export type TranslationInfoUpdateManyMutationInput = {
  isVolunteer?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isOriginal?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isParent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isChild?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isTranslationBonusChild?: Prisma.BoolFieldUpdateOperationsInput | boolean
  originalWorkno?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  parentWorkno?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  childWorknos?: Prisma.TranslationInfoUpdatechildWorknosInput | string[]
  lang?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type TranslationInfoUncheckedUpdateManyInput = {
  workId?: Prisma.StringFieldUpdateOperationsInput | string
  isVolunteer?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isOriginal?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isParent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isChild?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isTranslationBonusChild?: Prisma.BoolFieldUpdateOperationsInput | boolean
  originalWorkno?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  parentWorkno?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  childWorknos?: Prisma.TranslationInfoUpdatechildWorknosInput | string[]
  lang?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type TranslationInfoNullableScalarRelationFilter = {
  is?: Prisma.TranslationInfoWhereInput | null
  isNot?: Prisma.TranslationInfoWhereInput | null
}

export type StringNullableListFilter<$PrismaModel = never> = {
  equals?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  has?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  hasEvery?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  hasSome?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  isEmpty?: boolean
}

export type TranslationInfoCountOrderByAggregateInput = {
  workId?: Prisma.SortOrder
  isVolunteer?: Prisma.SortOrder
  isOriginal?: Prisma.SortOrder
  isParent?: Prisma.SortOrder
  isChild?: Prisma.SortOrder
  isTranslationBonusChild?: Prisma.SortOrder
  originalWorkno?: Prisma.SortOrder
  parentWorkno?: Prisma.SortOrder
  childWorknos?: Prisma.SortOrder
  lang?: Prisma.SortOrder
}

export type TranslationInfoMaxOrderByAggregateInput = {
  workId?: Prisma.SortOrder
  isVolunteer?: Prisma.SortOrder
  isOriginal?: Prisma.SortOrder
  isParent?: Prisma.SortOrder
  isChild?: Prisma.SortOrder
  isTranslationBonusChild?: Prisma.SortOrder
  originalWorkno?: Prisma.SortOrder
  parentWorkno?: Prisma.SortOrder
  lang?: Prisma.SortOrder
}

export type TranslationInfoMinOrderByAggregateInput = {
  workId?: Prisma.SortOrder
  isVolunteer?: Prisma.SortOrder
  isOriginal?: Prisma.SortOrder
  isParent?: Prisma.SortOrder
  isChild?: Prisma.SortOrder
  isTranslationBonusChild?: Prisma.SortOrder
  originalWorkno?: Prisma.SortOrder
  parentWorkno?: Prisma.SortOrder
  lang?: Prisma.SortOrder
}

export type TranslationInfoCreateNestedOneWithoutWorkInput = {
  create?: Prisma.XOR<Prisma.TranslationInfoCreateWithoutWorkInput, Prisma.TranslationInfoUncheckedCreateWithoutWorkInput>
  connectOrCreate?: Prisma.TranslationInfoCreateOrConnectWithoutWorkInput
  connect?: Prisma.TranslationInfoWhereUniqueInput
}

export type TranslationInfoUncheckedCreateNestedOneWithoutWorkInput = {
  create?: Prisma.XOR<Prisma.TranslationInfoCreateWithoutWorkInput, Prisma.TranslationInfoUncheckedCreateWithoutWorkInput>
  connectOrCreate?: Prisma.TranslationInfoCreateOrConnectWithoutWorkInput
  connect?: Prisma.TranslationInfoWhereUniqueInput
}

export type TranslationInfoUpdateOneWithoutWorkNestedInput = {
  create?: Prisma.XOR<Prisma.TranslationInfoCreateWithoutWorkInput, Prisma.TranslationInfoUncheckedCreateWithoutWorkInput>
  connectOrCreate?: Prisma.TranslationInfoCreateOrConnectWithoutWorkInput
  upsert?: Prisma.TranslationInfoUpsertWithoutWorkInput
  disconnect?: Prisma.TranslationInfoWhereInput | boolean
  delete?: Prisma.TranslationInfoWhereInput | boolean
  connect?: Prisma.TranslationInfoWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TranslationInfoUpdateToOneWithWhereWithoutWorkInput, Prisma.TranslationInfoUpdateWithoutWorkInput>, Prisma.TranslationInfoUncheckedUpdateWithoutWorkInput>
}

export type TranslationInfoUncheckedUpdateOneWithoutWorkNestedInput = {
  create?: Prisma.XOR<Prisma.TranslationInfoCreateWithoutWorkInput, Prisma.TranslationInfoUncheckedCreateWithoutWorkInput>
  connectOrCreate?: Prisma.TranslationInfoCreateOrConnectWithoutWorkInput
  upsert?: Prisma.TranslationInfoUpsertWithoutWorkInput
  disconnect?: Prisma.TranslationInfoWhereInput | boolean
  delete?: Prisma.TranslationInfoWhereInput | boolean
  connect?: Prisma.TranslationInfoWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TranslationInfoUpdateToOneWithWhereWithoutWorkInput, Prisma.TranslationInfoUpdateWithoutWorkInput>, Prisma.TranslationInfoUncheckedUpdateWithoutWorkInput>
}

export type TranslationInfoCreatechildWorknosInput = {
  set: string[]
}

export type TranslationInfoUpdatechildWorknosInput = {
  set?: string[]
  push?: string | string[]
}

export type TranslationInfoCreateWithoutWorkInput = {
  isVolunteer: boolean
  isOriginal: boolean
  isParent: boolean
  isChild: boolean
  isTranslationBonusChild: boolean
  originalWorkno?: string | null
  parentWorkno?: string | null
  childWorknos?: Prisma.TranslationInfoCreatechildWorknosInput | string[]
  lang?: string | null
}

export type TranslationInfoUncheckedCreateWithoutWorkInput = {
  isVolunteer: boolean
  isOriginal: boolean
  isParent: boolean
  isChild: boolean
  isTranslationBonusChild: boolean
  originalWorkno?: string | null
  parentWorkno?: string | null
  childWorknos?: Prisma.TranslationInfoCreatechildWorknosInput | string[]
  lang?: string | null
}

export type TranslationInfoCreateOrConnectWithoutWorkInput = {
  where: Prisma.TranslationInfoWhereUniqueInput
  create: Prisma.XOR<Prisma.TranslationInfoCreateWithoutWorkInput, Prisma.TranslationInfoUncheckedCreateWithoutWorkInput>
}

export type TranslationInfoUpsertWithoutWorkInput = {
  update: Prisma.XOR<Prisma.TranslationInfoUpdateWithoutWorkInput, Prisma.TranslationInfoUncheckedUpdateWithoutWorkInput>
  create: Prisma.XOR<Prisma.TranslationInfoCreateWithoutWorkInput, Prisma.TranslationInfoUncheckedCreateWithoutWorkInput>
  where?: Prisma.TranslationInfoWhereInput
}

export type TranslationInfoUpdateToOneWithWhereWithoutWorkInput = {
  where?: Prisma.TranslationInfoWhereInput
  data: Prisma.XOR<Prisma.TranslationInfoUpdateWithoutWorkInput, Prisma.TranslationInfoUncheckedUpdateWithoutWorkInput>
}

export type TranslationInfoUpdateWithoutWorkInput = {
  isVolunteer?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isOriginal?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isParent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isChild?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isTranslationBonusChild?: Prisma.BoolFieldUpdateOperationsInput | boolean
  originalWorkno?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  parentWorkno?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  childWorknos?: Prisma.TranslationInfoUpdatechildWorknosInput | string[]
  lang?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type TranslationInfoUncheckedUpdateWithoutWorkInput = {
  isVolunteer?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isOriginal?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isParent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isChild?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isTranslationBonusChild?: Prisma.BoolFieldUpdateOperationsInput | boolean
  originalWorkno?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  parentWorkno?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  childWorknos?: Prisma.TranslationInfoUpdatechildWorknosInput | string[]
  lang?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type TranslationInfoSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  workId?: boolean
  isVolunteer?: boolean
  isOriginal?: boolean
  isParent?: boolean
  isChild?: boolean
  isTranslationBonusChild?: boolean
  originalWorkno?: boolean
  parentWorkno?: boolean
  childWorknos?: boolean
  lang?: boolean
  work?: boolean | Prisma.WorkDefaultArgs<ExtArgs>
}, ExtArgs["result"]["translationInfo"]>

export type TranslationInfoSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  workId?: boolean
  isVolunteer?: boolean
  isOriginal?: boolean
  isParent?: boolean
  isChild?: boolean
  isTranslationBonusChild?: boolean
  originalWorkno?: boolean
  parentWorkno?: boolean
  childWorknos?: boolean
  lang?: boolean
  work?: boolean | Prisma.WorkDefaultArgs<ExtArgs>
}, ExtArgs["result"]["translationInfo"]>

export type TranslationInfoSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  workId?: boolean
  isVolunteer?: boolean
  isOriginal?: boolean
  isParent?: boolean
  isChild?: boolean
  isTranslationBonusChild?: boolean
  originalWorkno?: boolean
  parentWorkno?: boolean
  childWorknos?: boolean
  lang?: boolean
  work?: boolean | Prisma.WorkDefaultArgs<ExtArgs>
}, ExtArgs["result"]["translationInfo"]>

export type TranslationInfoSelectScalar = {
  workId?: boolean
  isVolunteer?: boolean
  isOriginal?: boolean
  isParent?: boolean
  isChild?: boolean
  isTranslationBonusChild?: boolean
  originalWorkno?: boolean
  parentWorkno?: boolean
  childWorknos?: boolean
  lang?: boolean
}

export type TranslationInfoOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"workId" | "isVolunteer" | "isOriginal" | "isParent" | "isChild" | "isTranslationBonusChild" | "originalWorkno" | "parentWorkno" | "childWorknos" | "lang", ExtArgs["result"]["translationInfo"]>
export type TranslationInfoInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  work?: boolean | Prisma.WorkDefaultArgs<ExtArgs>
}
export type TranslationInfoIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  work?: boolean | Prisma.WorkDefaultArgs<ExtArgs>
}
export type TranslationInfoIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  work?: boolean | Prisma.WorkDefaultArgs<ExtArgs>
}

export type $TranslationInfoPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TranslationInfo"
  objects: {
    work: Prisma.$WorkPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    workId: string
    isVolunteer: boolean
    isOriginal: boolean
    isParent: boolean
    isChild: boolean
    isTranslationBonusChild: boolean
    originalWorkno: string | null
    parentWorkno: string | null
    childWorknos: string[]
    lang: string | null
  }, ExtArgs["result"]["translationInfo"]>
  composites: {}
}

export type TranslationInfoGetPayload<S extends boolean | null | undefined | TranslationInfoDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TranslationInfoPayload, S>

export type TranslationInfoCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TranslationInfoFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TranslationInfoCountAggregateInputType | true
  }

export interface TranslationInfoDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TranslationInfo'], meta: { name: 'TranslationInfo' } }
  /**
   * Find zero or one TranslationInfo that matches the filter.
   * @param {TranslationInfoFindUniqueArgs} args - Arguments to find a TranslationInfo
   * @example
   * // Get one TranslationInfo
   * const translationInfo = await prisma.translationInfo.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TranslationInfoFindUniqueArgs>(args: Prisma.SelectSubset<T, TranslationInfoFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TranslationInfoClient<runtime.Types.Result.GetResult<Prisma.$TranslationInfoPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TranslationInfo that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TranslationInfoFindUniqueOrThrowArgs} args - Arguments to find a TranslationInfo
   * @example
   * // Get one TranslationInfo
   * const translationInfo = await prisma.translationInfo.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TranslationInfoFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TranslationInfoFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TranslationInfoClient<runtime.Types.Result.GetResult<Prisma.$TranslationInfoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TranslationInfo that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TranslationInfoFindFirstArgs} args - Arguments to find a TranslationInfo
   * @example
   * // Get one TranslationInfo
   * const translationInfo = await prisma.translationInfo.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TranslationInfoFindFirstArgs>(args?: Prisma.SelectSubset<T, TranslationInfoFindFirstArgs<ExtArgs>>): Prisma.Prisma__TranslationInfoClient<runtime.Types.Result.GetResult<Prisma.$TranslationInfoPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TranslationInfo that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TranslationInfoFindFirstOrThrowArgs} args - Arguments to find a TranslationInfo
   * @example
   * // Get one TranslationInfo
   * const translationInfo = await prisma.translationInfo.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TranslationInfoFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TranslationInfoFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TranslationInfoClient<runtime.Types.Result.GetResult<Prisma.$TranslationInfoPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TranslationInfos that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TranslationInfoFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TranslationInfos
   * const translationInfos = await prisma.translationInfo.findMany()
   * 
   * // Get first 10 TranslationInfos
   * const translationInfos = await prisma.translationInfo.findMany({ take: 10 })
   * 
   * // Only select the `workId`
   * const translationInfoWithWorkIdOnly = await prisma.translationInfo.findMany({ select: { workId: true } })
   * 
   */
  findMany<T extends TranslationInfoFindManyArgs>(args?: Prisma.SelectSubset<T, TranslationInfoFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TranslationInfoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TranslationInfo.
   * @param {TranslationInfoCreateArgs} args - Arguments to create a TranslationInfo.
   * @example
   * // Create one TranslationInfo
   * const TranslationInfo = await prisma.translationInfo.create({
   *   data: {
   *     // ... data to create a TranslationInfo
   *   }
   * })
   * 
   */
  create<T extends TranslationInfoCreateArgs>(args: Prisma.SelectSubset<T, TranslationInfoCreateArgs<ExtArgs>>): Prisma.Prisma__TranslationInfoClient<runtime.Types.Result.GetResult<Prisma.$TranslationInfoPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TranslationInfos.
   * @param {TranslationInfoCreateManyArgs} args - Arguments to create many TranslationInfos.
   * @example
   * // Create many TranslationInfos
   * const translationInfo = await prisma.translationInfo.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TranslationInfoCreateManyArgs>(args?: Prisma.SelectSubset<T, TranslationInfoCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TranslationInfos and returns the data saved in the database.
   * @param {TranslationInfoCreateManyAndReturnArgs} args - Arguments to create many TranslationInfos.
   * @example
   * // Create many TranslationInfos
   * const translationInfo = await prisma.translationInfo.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TranslationInfos and only return the `workId`
   * const translationInfoWithWorkIdOnly = await prisma.translationInfo.createManyAndReturn({
   *   select: { workId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TranslationInfoCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TranslationInfoCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TranslationInfoPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TranslationInfo.
   * @param {TranslationInfoDeleteArgs} args - Arguments to delete one TranslationInfo.
   * @example
   * // Delete one TranslationInfo
   * const TranslationInfo = await prisma.translationInfo.delete({
   *   where: {
   *     // ... filter to delete one TranslationInfo
   *   }
   * })
   * 
   */
  delete<T extends TranslationInfoDeleteArgs>(args: Prisma.SelectSubset<T, TranslationInfoDeleteArgs<ExtArgs>>): Prisma.Prisma__TranslationInfoClient<runtime.Types.Result.GetResult<Prisma.$TranslationInfoPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TranslationInfo.
   * @param {TranslationInfoUpdateArgs} args - Arguments to update one TranslationInfo.
   * @example
   * // Update one TranslationInfo
   * const translationInfo = await prisma.translationInfo.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TranslationInfoUpdateArgs>(args: Prisma.SelectSubset<T, TranslationInfoUpdateArgs<ExtArgs>>): Prisma.Prisma__TranslationInfoClient<runtime.Types.Result.GetResult<Prisma.$TranslationInfoPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TranslationInfos.
   * @param {TranslationInfoDeleteManyArgs} args - Arguments to filter TranslationInfos to delete.
   * @example
   * // Delete a few TranslationInfos
   * const { count } = await prisma.translationInfo.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TranslationInfoDeleteManyArgs>(args?: Prisma.SelectSubset<T, TranslationInfoDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TranslationInfos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TranslationInfoUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TranslationInfos
   * const translationInfo = await prisma.translationInfo.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TranslationInfoUpdateManyArgs>(args: Prisma.SelectSubset<T, TranslationInfoUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TranslationInfos and returns the data updated in the database.
   * @param {TranslationInfoUpdateManyAndReturnArgs} args - Arguments to update many TranslationInfos.
   * @example
   * // Update many TranslationInfos
   * const translationInfo = await prisma.translationInfo.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TranslationInfos and only return the `workId`
   * const translationInfoWithWorkIdOnly = await prisma.translationInfo.updateManyAndReturn({
   *   select: { workId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TranslationInfoUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TranslationInfoUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TranslationInfoPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TranslationInfo.
   * @param {TranslationInfoUpsertArgs} args - Arguments to update or create a TranslationInfo.
   * @example
   * // Update or create a TranslationInfo
   * const translationInfo = await prisma.translationInfo.upsert({
   *   create: {
   *     // ... data to create a TranslationInfo
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TranslationInfo we want to update
   *   }
   * })
   */
  upsert<T extends TranslationInfoUpsertArgs>(args: Prisma.SelectSubset<T, TranslationInfoUpsertArgs<ExtArgs>>): Prisma.Prisma__TranslationInfoClient<runtime.Types.Result.GetResult<Prisma.$TranslationInfoPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TranslationInfos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TranslationInfoCountArgs} args - Arguments to filter TranslationInfos to count.
   * @example
   * // Count the number of TranslationInfos
   * const count = await prisma.translationInfo.count({
   *   where: {
   *     // ... the filter for the TranslationInfos we want to count
   *   }
   * })
  **/
  count<T extends TranslationInfoCountArgs>(
    args?: Prisma.Subset<T, TranslationInfoCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TranslationInfoCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TranslationInfo.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TranslationInfoAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TranslationInfoAggregateArgs>(args: Prisma.Subset<T, TranslationInfoAggregateArgs>): Prisma.PrismaPromise<GetTranslationInfoAggregateType<T>>

  /**
   * Group by TranslationInfo.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TranslationInfoGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TranslationInfoGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TranslationInfoGroupByArgs['orderBy'] }
      : { orderBy?: TranslationInfoGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TranslationInfoGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTranslationInfoGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TranslationInfo model
 */
readonly fields: TranslationInfoFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TranslationInfo.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TranslationInfoClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  work<T extends Prisma.WorkDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.WorkDefaultArgs<ExtArgs>>): Prisma.Prisma__WorkClient<runtime.Types.Result.GetResult<Prisma.$WorkPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TranslationInfo model
 */
export interface TranslationInfoFieldRefs {
  readonly workId: Prisma.FieldRef<"TranslationInfo", 'String'>
  readonly isVolunteer: Prisma.FieldRef<"TranslationInfo", 'Boolean'>
  readonly isOriginal: Prisma.FieldRef<"TranslationInfo", 'Boolean'>
  readonly isParent: Prisma.FieldRef<"TranslationInfo", 'Boolean'>
  readonly isChild: Prisma.FieldRef<"TranslationInfo", 'Boolean'>
  readonly isTranslationBonusChild: Prisma.FieldRef<"TranslationInfo", 'Boolean'>
  readonly originalWorkno: Prisma.FieldRef<"TranslationInfo", 'String'>
  readonly parentWorkno: Prisma.FieldRef<"TranslationInfo", 'String'>
  readonly childWorknos: Prisma.FieldRef<"TranslationInfo", 'String[]'>
  readonly lang: Prisma.FieldRef<"TranslationInfo", 'String'>
}
    

// Custom InputTypes
/**
 * TranslationInfo findUnique
 */
export type TranslationInfoFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TranslationInfo
   */
  select?: Prisma.TranslationInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TranslationInfo
   */
  omit?: Prisma.TranslationInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationInfoInclude<ExtArgs> | null
  /**
   * Filter, which TranslationInfo to fetch.
   */
  where: Prisma.TranslationInfoWhereUniqueInput
}

/**
 * TranslationInfo findUniqueOrThrow
 */
export type TranslationInfoFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TranslationInfo
   */
  select?: Prisma.TranslationInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TranslationInfo
   */
  omit?: Prisma.TranslationInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationInfoInclude<ExtArgs> | null
  /**
   * Filter, which TranslationInfo to fetch.
   */
  where: Prisma.TranslationInfoWhereUniqueInput
}

/**
 * TranslationInfo findFirst
 */
export type TranslationInfoFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TranslationInfo
   */
  select?: Prisma.TranslationInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TranslationInfo
   */
  omit?: Prisma.TranslationInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationInfoInclude<ExtArgs> | null
  /**
   * Filter, which TranslationInfo to fetch.
   */
  where?: Prisma.TranslationInfoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TranslationInfos to fetch.
   */
  orderBy?: Prisma.TranslationInfoOrderByWithRelationInput | Prisma.TranslationInfoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TranslationInfos.
   */
  cursor?: Prisma.TranslationInfoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TranslationInfos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TranslationInfos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TranslationInfos.
   */
  distinct?: Prisma.TranslationInfoScalarFieldEnum | Prisma.TranslationInfoScalarFieldEnum[]
}

/**
 * TranslationInfo findFirstOrThrow
 */
export type TranslationInfoFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TranslationInfo
   */
  select?: Prisma.TranslationInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TranslationInfo
   */
  omit?: Prisma.TranslationInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationInfoInclude<ExtArgs> | null
  /**
   * Filter, which TranslationInfo to fetch.
   */
  where?: Prisma.TranslationInfoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TranslationInfos to fetch.
   */
  orderBy?: Prisma.TranslationInfoOrderByWithRelationInput | Prisma.TranslationInfoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TranslationInfos.
   */
  cursor?: Prisma.TranslationInfoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TranslationInfos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TranslationInfos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TranslationInfos.
   */
  distinct?: Prisma.TranslationInfoScalarFieldEnum | Prisma.TranslationInfoScalarFieldEnum[]
}

/**
 * TranslationInfo findMany
 */
export type TranslationInfoFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TranslationInfo
   */
  select?: Prisma.TranslationInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TranslationInfo
   */
  omit?: Prisma.TranslationInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationInfoInclude<ExtArgs> | null
  /**
   * Filter, which TranslationInfos to fetch.
   */
  where?: Prisma.TranslationInfoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TranslationInfos to fetch.
   */
  orderBy?: Prisma.TranslationInfoOrderByWithRelationInput | Prisma.TranslationInfoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TranslationInfos.
   */
  cursor?: Prisma.TranslationInfoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TranslationInfos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TranslationInfos.
   */
  skip?: number
  distinct?: Prisma.TranslationInfoScalarFieldEnum | Prisma.TranslationInfoScalarFieldEnum[]
}

/**
 * TranslationInfo create
 */
export type TranslationInfoCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TranslationInfo
   */
  select?: Prisma.TranslationInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TranslationInfo
   */
  omit?: Prisma.TranslationInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationInfoInclude<ExtArgs> | null
  /**
   * The data needed to create a TranslationInfo.
   */
  data: Prisma.XOR<Prisma.TranslationInfoCreateInput, Prisma.TranslationInfoUncheckedCreateInput>
}

/**
 * TranslationInfo createMany
 */
export type TranslationInfoCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TranslationInfos.
   */
  data: Prisma.TranslationInfoCreateManyInput | Prisma.TranslationInfoCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TranslationInfo createManyAndReturn
 */
export type TranslationInfoCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TranslationInfo
   */
  select?: Prisma.TranslationInfoSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TranslationInfo
   */
  omit?: Prisma.TranslationInfoOmit<ExtArgs> | null
  /**
   * The data used to create many TranslationInfos.
   */
  data: Prisma.TranslationInfoCreateManyInput | Prisma.TranslationInfoCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationInfoIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TranslationInfo update
 */
export type TranslationInfoUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TranslationInfo
   */
  select?: Prisma.TranslationInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TranslationInfo
   */
  omit?: Prisma.TranslationInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationInfoInclude<ExtArgs> | null
  /**
   * The data needed to update a TranslationInfo.
   */
  data: Prisma.XOR<Prisma.TranslationInfoUpdateInput, Prisma.TranslationInfoUncheckedUpdateInput>
  /**
   * Choose, which TranslationInfo to update.
   */
  where: Prisma.TranslationInfoWhereUniqueInput
}

/**
 * TranslationInfo updateMany
 */
export type TranslationInfoUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TranslationInfos.
   */
  data: Prisma.XOR<Prisma.TranslationInfoUpdateManyMutationInput, Prisma.TranslationInfoUncheckedUpdateManyInput>
  /**
   * Filter which TranslationInfos to update
   */
  where?: Prisma.TranslationInfoWhereInput
  /**
   * Limit how many TranslationInfos to update.
   */
  limit?: number
}

/**
 * TranslationInfo updateManyAndReturn
 */
export type TranslationInfoUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TranslationInfo
   */
  select?: Prisma.TranslationInfoSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TranslationInfo
   */
  omit?: Prisma.TranslationInfoOmit<ExtArgs> | null
  /**
   * The data used to update TranslationInfos.
   */
  data: Prisma.XOR<Prisma.TranslationInfoUpdateManyMutationInput, Prisma.TranslationInfoUncheckedUpdateManyInput>
  /**
   * Filter which TranslationInfos to update
   */
  where?: Prisma.TranslationInfoWhereInput
  /**
   * Limit how many TranslationInfos to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationInfoIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TranslationInfo upsert
 */
export type TranslationInfoUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TranslationInfo
   */
  select?: Prisma.TranslationInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TranslationInfo
   */
  omit?: Prisma.TranslationInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationInfoInclude<ExtArgs> | null
  /**
   * The filter to search for the TranslationInfo to update in case it exists.
   */
  where: Prisma.TranslationInfoWhereUniqueInput
  /**
   * In case the TranslationInfo found by the `where` argument doesn't exist, create a new TranslationInfo with this data.
   */
  create: Prisma.XOR<Prisma.TranslationInfoCreateInput, Prisma.TranslationInfoUncheckedCreateInput>
  /**
   * In case the TranslationInfo was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TranslationInfoUpdateInput, Prisma.TranslationInfoUncheckedUpdateInput>
}

/**
 * TranslationInfo delete
 */
export type TranslationInfoDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TranslationInfo
   */
  select?: Prisma.TranslationInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TranslationInfo
   */
  omit?: Prisma.TranslationInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationInfoInclude<ExtArgs> | null
  /**
   * Filter which TranslationInfo to delete.
   */
  where: Prisma.TranslationInfoWhereUniqueInput
}

/**
 * TranslationInfo deleteMany
 */
export type TranslationInfoDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TranslationInfos to delete
   */
  where?: Prisma.TranslationInfoWhereInput
  /**
   * Limit how many TranslationInfos to delete.
   */
  limit?: number
}

/**
 * TranslationInfo without action
 */
export type TranslationInfoDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TranslationInfo
   */
  select?: Prisma.TranslationInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TranslationInfo
   */
  omit?: Prisma.TranslationInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationInfoInclude<ExtArgs> | null
}
