
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.ts'
export { Prisma }
export * as $Enums from './enums.ts'
export * from './enums.ts';
/**
 * Model Work
 * 
 */
export type Work = Prisma.WorkModel
/**
 * Model Circle
 * 
 */
export type Circle = Prisma.CircleModel
/**
 * Model Series
 * 
 */
export type Series = Prisma.SeriesModel
/**
 * Model Artist
 * 
 */
export type Artist = Prisma.ArtistModel
/**
 * Model Illustrator
 * 
 */
export type Illustrator = Prisma.IllustratorModel
/**
 * Model Genre
 * 
 */
export type Genre = Prisma.GenreModel
/**
 * Model SubtitlesData
 * 
 */
export type SubtitlesData = Prisma.SubtitlesDataModel
/**
 * Model TranslationInfo
 * 
 */
export type TranslationInfo = Prisma.TranslationInfoModel
